Take A Bow
----------
'Madonna Take A Bow Lyrics'

Take a bow, the night is over

This masquerade is getting older

Light are low, the curtains down

There's no one here

[there's no one here, there's no one in the crowd]

Say your lines but do you feel them

Do you mean what you say when there's no one around [no one around]

Watching you, watching me, one lonely star

[one lonely star you don't know who you are]

Chorus:

Ive always been in love with you [always with you]

I guess youve always known it's true [you know it's true]

You took my love for granted, why oh why

The show is over, say good-bye

Say good-bye [bye bye], say good-bye

Make them laugh, it comes so easy

When you get to the part

Where you're breaking my heart [breaking my heart]

Hide behind your smile, all the world loves a clown

[just make em smile the whole world loves a clown]

Wish you well, I cannot stay

You deserve an award for the role that you played [role that you played]

No more masquerade, you're one lonely star

[one lonely star and you don't know who you are]

(chorus, repeat)

Say good-bye [bye bye], say good-bye

All the world is a stage [world is a stage]

And everyone has their part [has their part]

But how was I to know which way the storyd go

How was I to know you'd break

[youd break, you'd break, you'd break]

Youd break my heart

Ive always been in love with you

[Ive always been in love with you]

Guess youve always known

You took my love for granted, why oh why

The show is over, say good-bye

(chorus)

Say good-bye [bye bye], say good-bye

Say good-bye

