select * from order_;
select * from header;
select * from orderheader;

select * from orderheader where orderref='order0';
select orderref from orderheader where (orderref='order0' or orderref='order10' or orderref = 'order20');

SELECT ORDERHEADER.ORDERREF FROM HEADER, ORDERHEADER WHERE (ORDERHEADER.HID = HEADER.ORDERHEADER_HID) AND (ORDERHEADER.ORDERREF='order0' or ORDERHEADER.ORDERREF='order10' or ORDERHEADER.ORDERREF='order20' or ORDERHEADER.ORDERREF='order30')
SELECT ORDERHEADER.ORDERREF FROM HEADER, ORDERHEADER WHERE (ORDERHEADER.HID = HEADER.ORDERHEADER_HID) AND (ORDERHEADER.ORDERREF='order0');

SELECT HEADER.STATUS, HEADER.STATUSCHANGED, ORDERHEADER.ORDERREF FROM HEADER, ORDERHEADER WHERE ORDERHEADER.HID = HEADER.ORDERHEADER_HID;

SELECT ORDERHEADER.ORDERREF FROM HEADER, ORDERHEADER WHERE ORDERHEADER.HID = HEADER.ORDERHEADER_HID ;
SELECT ORDERHEADER.HID, ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF='order0');

delete from order_;
delete from header;
delete from orderheader;

select * from user_constraints where table_name='HEADER';

-- IPCUtil Test
SELECT HEADER.PLANUNIQUEID, ORDER_.HID FROM ORDER_ INNER JOIN HEADER ON ORDER_.HEADER_HID = HEADER.HID INNER JOIN ORDERHEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE ORDERHEADER.ORDERREF = 'AOPD-AUTOTEST-1309495552921';
SELECT EXECUTIONPLAN.HID FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.UNIQUEID='AOPD-AUTOTEST-1309495552921-1309495555390';
SELECT AUDITITEM.HID FROM AUDITITEM WHERE AUDITITEM.Key = 'AOPD-AUTOTEST-1309495552921';
SELECT ORDER_.HEADER_HID, ORDER_.REQUEST_HID FROM ORDER_ WHERE ORDER_.HID = 1;
SELECT ORDER_TO_LINETYPE.LINETYPE_HID FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 1;
SELECT * FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 1;
DELETE FROM ORDERLINE WHERE ORDERLINE.HID = 1;
SELECT * FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 1
DELETE FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 1;


SELECT * FROM ORDER_;
SELECT * FROM HEADER;
SELECT * FROM ORDERHEADER;
SELECT * FROM HEADER WHERE HEADER.STATUSCHANGED < to_date('2011-12-14 07:31:00','yyyy-mm-dd hh24:mi:ss');

-- SQL INNER JOIN
SELECT ORDERHEADER.CUSTOMERREF, ORDERHEADER.ORDERREF, HEADER.STATUS HEADER_STATUS, HEADER.HID HEADER_HID 
FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE ORDERHEADER.ORDERREF='order0';

SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID;
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF = 'order1' OR ORDERHEADER.ORDERREF = 'order2' OR ORDERHEADER.ORDERREF = 'order0');
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF LIKE 'order0%');
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF LIKE 'order0%' OR ORDERHEADER.ORDERREF LIKE 'order2%' OR ORDERHEADER.ORDERREF LIKE 'order1%');
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF = 'order1' OR ORDERHEADER.ORDERREF LIKE 'order0%' OR ORDERHEADER.ORDERREF = 'order2');
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF = 'order1' OR ORDERHEADER.ORDERREF LIKE 'order0%' OR ORDERHEADER.ORDERREF = 'order2') AND (HEADER.STATUS = 'Cancel' OR HEADER.STATUS = 'Submitted' OR HEADER.STATUS = 'Complete');
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF LIKE '%');
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF LIKE '%') AND (HEADER.STATUS = 'Cancel' OR HEADER.STATUS = 'Submitted' OR HEADER.STATUS = 'Complete')
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE (ORDERHEADER.ORDERREF LIKE '%') AND (HEADER.STATUS = 'Cancel' OR HEADER.STATUS = 'Submitted' OR HEADER.STATUS = 'Complete') AND (HEADER.STATUSCHANGED < to_date('2011-12-14 07:31:00', 'yyyy-mm-dd hh24:mi:ss'));
SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID 
WHERE (ORDERHEADER.ORDERREF = 'order1' OR ORDERHEADER.ORDERREF LIKE 'order0%' OR ORDERHEADER.ORDERREF = 'order2') 
AND (HEADER.STATUS = 'Cancel' OR HEADER.STATUS = 'Submitted' OR HEADER.STATUS = 'Complete') 
AND (HEADER.STATUSCHANGED < to_date('2011-12-14 07:31:00', 'yyyy-mm-dd hh24:mi:ss'));

SELECT * FROM ORDER_;
SELECT HEADER.PLANUNIQUEID, ORDER_.HID, ORDERHEADER.ORDERREF FROM ORDER_ INNER JOIN HEADER ON ORDER_.HEADER_HID = HEADER.HID INNER JOIN ORDERHEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE ORDERHEADER.ORDERREF = 'order0';
SELECT EXECUTIONPLAN.HID FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.UNIQUEID='ep1';

SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE HEADER.PLANUNIQUEID = 'ep1';

SELECT * FROM EXECUTIONPLAN;
SELECT * FROM COMPONENT;
SELECT * FROM COMPONENT_TO_OBJECTTYPE;
SELECT * FROM OBJECTTYPE;             
SELECT * FROM PROCESS;
SELECT COMPONENT.HID, OBJECTTYPE.ID FROM COMPONENT INNER JOIN COMPONENT_TO_OBJECTTYPE ON COMPONENT_TO_OBJECTTYPE.COMPONENT_HID = COMPONENT.HID INNER JOIN OBJECTTYPE ON OBJECTTYPE.HID = COMPONENT_TO_OBJECTTYPE.OBJECTTYPE_HID WHERE COMPONENT.UNIQUEID = 'PRO01' ;
SELECT * FROM EXECUTIONPLANITEMTYPE;
SELECT DISTINCT EXECUTIONPLAN.UNIQUEID FROM EXECUTIONPLAN INNER JOIN EXECUTIONPLANITEMTYPE ON EXECUTIONPLANITEMTYPE.PLAN_HID = EXECUTIONPLAN.HID WHERE EXECUTIONPLANITEMTYPE.UNIQUECOMPID = 'PROC1'

SELECT * FROM AUDITITEM;
SELECT * FROM RESOURCEBUNDLEPARAMS;
SELECT AUDITITEM.HID FROM AUDITITEM WHERE AUDITITEM.Key = 'ep1'
DELETE FROM RESOURCEBUNDLEPARAMS WHERE RESOURCEBUNDLEPARAMS.AUDITITEM_HID = 1
DELETE FROM AUDITITEM WHERE AUDITITEM.HID = 1;
SELECT AUDITITEM.HID FROM AUDITITEM WHERE AUDITITEM.PARENT_HID = 1

SELECT * FROM ORDER_;
SELECT * FROM EXECUTIONPLAN;
SELECT * FROM COMPONENT;
SELECT * FROM PROCESS ;
-- Complete clean PROCESS
SELECT * FROM PROCESS WHERE PROCESS.MANAGEDENTITYPK_ID = 'hid2';
SELECT * FROM PROCESSVERSION WHERE PROCESSVERSION.HID = 47;
SELECT * FROM PROCESSVERSION_TO_MILESTONE;
SELECT * FROM PROCESSVERSION_TO_SECTION;
SELECT * FROM PROCESSSECTIONTYPE;

SELECT PROCESS.PROCESSVERSION_HID FROM PROCESS WHERE PROCESS.MANAGEDENTITYPK_ID = 'hid2'
DELETE FROM PROCESS WHERE PROCESS.MANAGEDENTITYPK_ID = 'hid2'
SELECT PROCESSVERSION_TO_SECTION.PROCESSSECTIONTYPE_HID FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 47
DELETE FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 47
DELETE FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 47
SELECT PROCESSVERSION_TO_MILESTONE.MILESTONE_HID FROM PROCESSVERSION_TO_MILESTONE WHERE PROCESSVERSION_TO_MILESTONE.PROCESSVERSION_HID = 47
DELETE FROM PROCESSVERSION_TO_MILESTONE WHERE PROCESSVERSION_TO_MILESTONE.
DELETE FROM PROCESSVERSION WHERE PROCESSVERSION.HID = 47

SELECT * FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 47
SELECT * FROM PROCESSJEOPARDYTYPE WHERE PROCESSJEOPARDYTYPE.PROCESSSECTIONTYPE_HID = 47
SELECT PROCESSJEOPARDYTYPE.HID FROM PROCESSJEOPARDYTYPE WHERE PROCESSJEOPARDYTYPE.PROCESSSECTIONTYPE_HID = 47
SELECT PROCESSSECTIONTYPE.SCHEDULEABLEITEM_HID FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 47
SELECT * FROM SCHEDULEABLEITEM WHERE SCHEDULEABLEITEM.HID = 160;
SELECT RESOURCETYPE.HID FROM RESOURCETYPE WHERE RESOURCETYPE.SCHEDULEABLEITEM_HID = 160
SELECT * FROM RESOURCETYPE;    
DELETE FROM RESOURCETYPE WHERE RESOURCETYPE.HID = 1
SELECT * FROM MILESTONETYPE WHERE MILESTONETYPE.HID = 93;
SELECT MILESTONETYPE_PROPERTY.PROPERTY_HID FROM MILESTONETYPE_PROPERTY WHERE MILESTONETYPE_PROPERTY.MILESTONETYPE_HID = 93
SELECT * FROM PROPERTY WHERE PROPERTY.HID = 588;
DELETE FROM MILESTONETYPE_PROPERTY WHERE MILESTONETYPE_PROPERTY.MILESTONETYPE_HID = 93
DELETE FROM PROPERTY WHERE PROPERTY.HID = 588
SELECT MILESTONETYPE_FIELD.FIELD_HID FROM MILESTONETYPE_FIELD WHERE MILESTONETYPE_FIELD.MILESTONETYPE_HID = 92
SELECT * FROM MILESTONETYPE WHERE MILESTONETYPE.HID = 92;
SELECT * FROM FIELD;
DELETE FROM MILESTONETYPE_FIELD WHERE MILESTONETYPE_FIELD.MILESTONETYPE_HID = 93
DELETE FROM FIELD WHERE FIELD.HID = 93
SELECT MILESTONETYPE.POINTTYPE_HID FROM MILESTONETYPE WHERE MILESTONETYPE.HID = 93
DELETE FROM MILESTONETYPE WHERE MILESTONETYPE.HID = 93

SELECT * FROM POINTTYPE WHERE POINTTYPE.HID = 132;
SELECT DEPENDENCY.HID FROM DEPENDENCY WHERE DEPENDENCY.POINTTYPE_HID = 132
SELECT * FROM DEPENDENCY WHERE DEPENDENCY.HID = 1;
SELECT DEPENDENCY.EXTERNALDEPENDENCYTYPE_HID, DEPENDENCY.PLANITEMDEPENDENCYTYPE_HID, DEPENDENCY.STARTTIMEDEPENDENCYTYPE_HID FROM DEPENDENCY WHERE DEPENDENCY.HID = 1
DELETE FROM DEPENDENCY WHERE DEPENDENCY.HID = 1
SELECT EXTERNALDEPENDENCYTYPE.FULFILMENTSYSTEMTYPE_HID FROM EXTERNALDEPENDENCYTYPE WHERE EXTERNALDEPENDENCYTYPE.HID = 1
DELETE FROM EXTERNALDEPENDENCYTYPE WHERE EXTERNALDEPENDENCYTYPE.HID = 1
SELECT * FROM PLANITEMDEPENDENCYTYPE;
DELETE FROM PLANITEMDEPENDENCYTYPE WHERE PLANITEMDEPENDENCYTYPE.HID = 1
SELECT STARTTIMEDEPENDENCYTYPE.JEOPARDYSUPERTYPE_HID FROM STARTTIMEDEPENDENCYTYPE WHERE STARTTIMEDEPENDENCYTYPE.HID = 3
DELETE FROM STARTTIMEDEPENDENCYTYPE WHERE STARTTIMEDEPENDENCYTYPE.HID = 3

DELETE FROM POINTTYPE WHERE POINTTYPE.HID = 132
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME LIKE 'FKFEEE%'

SELECT * FROM FULFILMENTSYSTEMTYPE;
SELECT FSYSTEMTYPE_PROPERTY.PROPERTY_HID FROM FSYSTEMTYPE_PROPERTY WHERE FSYSTEMTYPE_PROPERTY.FULFILMENTSYSTEMTYPE_HID = 588
DELETE FROM FSYSTEMTYPE_PROPERTY WHERE FSYSTEMTYPE_PROPERTY.FULFILMENTSYSTEMTYPE_HID = 588
DELETE FROM FULFILMENTSYSTEMTYPE WHERE FULFILMENTSYSTEMTYPE.HID = 11231313

SELECT * FROM JEOPARDYSUPERTYPE;
SELECT * FROM JEOPARDYSUPERTYPE_TO_DEF;
SELECT JEOPARDYSUPERTYPE_TO_DEF.JEOPARDYDEFTYPE_HID FROM JEOPARDYSUPERTYPE_TO_DEF WHERE JEOPARDYSUPERTYPE_TO_DEF.JEOPARDYSUPERTYPE_HID = 10
DELETE FROM JEOPARDYSUPERTYPE_TO_DEF WHERE JEOPARDYSUPERTYPE_TO_DEF.JEOPARDYSUPERTYPE_HID = 1231321
DELETE FROM JEOPARDYSUPERTYPE WHERE JEOPARDYSUPERTYPE.HID = 1123123

SELECT * FROM JEOPARDYDEFTYPE WHERE JEOPARDYDEFTYPE.HID = 3;
SELECT * FROM ACTIONS;
DELETE FROM ACTIONS WHERE ACTIONS.JEOPARDYDEFTYPE_HID = 3
DELETE FROM JEOPARDYDEFTYPE WHERE JEOPARDYDEFTYPE.HID = 1231231

SELECT * FROM PROCESSJEOPARDYTYPE;
SELECT PROCESSJEOPARDYTYPE.ENDDATE_HID, PROCESSJEOPARDYTYPE.MUSTHAVESTARTEDBEFORE_HID, PROCESSJEOPARDYTYPE.MUSTSTARTON_HID, PROCESSJEOPARDYTYPE.MONITORINGTYPE_HID, PROCESSJEOPARDYTYPE.CONTINGENCY_HID, PROCESSJEOPARDYTYPE.REPORTING_HID, PROCESSJEOPARDYTYPE.MAXIMUM_HID, PROCESSJEOPARDYTYPE.TYPICAL_HID FROM PROCESSJEOPARDYTYPE WHERE PROCESSJEOPARDYTYPE.HID = 1
DELETE FROM PROCESSJEOPARDYTYPE WHERE PROCESSJEOPARDYTYPE.HID = 1
SELECT * FROM JEOPARDYSUPERTYPE;

SELECT * FROM FULFILMENTPROC;
SELECT FULFILMENTPROC_FIELD.FIELD_HID FROM FULFILMENTPROC_FIELD WHERE FULFILMENTPROC_FIELD.FULFILMENTPROC_HID = 209
DELETE FROM FULFILMENTPROC_FIELD WHERE FULFILMENTPROC_FIELD.FULFILMENTPROC_HID = 2131321313
SELECT FULFILMENTPROC.FULFILMENTSYSTEMTYPE_HID FROM FULFILMENTPROC WHERE FULFILMENTPROC.HID = 1

SELECT * FROM COMPONENT;
SELECT * FROM COMPONENT_TO_OBJECTTYPE;
SELECT * FROM OBJECTTYPE;
SELECT COMPONENT_TO_OBJECTTYPE.OBJECTTYPE_HID FROM COMPONENT_TO_OBJECTTYPE WHERE COMPONENT_TO_OBJECTTYPE.COMPONENT_HID = 14
DELETE FROM COMPONENT_TO_OBJECTTYPE WHERE COMPONENT_TO_OBJECTTYPE.COMPONENT_HID = 14
DELETE FROM OBJECTTYPE WHERE OBJECTTYPE.HID = 15

SELECT * FROM COMPONENT WHERE COMPONENT.HID = 2;
SELECT * FROM COMPONENTUSERS WHERE COMPONENTUSERS.COMPONENT_HID = 2;
SELECT * FROM COMPONENTGROUPS WHERE COMPONENTGROUPS.COMPONENT_HID = 2;
SELECT * FROM COMPONENT_TO_OBJECTTYPE WHERE COMPONENT_TO_OBJECTTYPE.COMPONENT_HID = 2
DELETE FROM COMPONENT_TO_OBJECTTYPE WHERE COMPONENT_TO_OBJECTTYPE.COMPONENT_HID = 2
DELETE FROM COMPONENTUSERS WHERE COMPONENTUSERS.COMPONENT_HID = 2
DELETE FROM COMPONENTGROUPS WHERE COMPONENTGROUPS.COMPONENT_HID = 2
DELETE FROM COMPONENT WHERE COMPONENT.HID = 2

SELECT * FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.HID = 35;
SELECT EXECUTIONPLAN.FULFILMENTPROC_HID FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.HID = 35
SELECT * FROM FULFILMENTPROC WHERE FULFILMENTPROC.P
DELETE FROM FULFILMENTPROC WHERE FULFILMENTPROC.HID = 218

SELECT EXECUTIONPLAN.JEOPARDYINFOTYPE_HID FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.HID = 35

SELECT * FROM PLAN_TO_UDFTYPE;
SELECT * FROM UDFTYPE;
SELECT PLAN_TO_UDFTYPE.UDFTYPE_HID FROM PLAN_TO_UDFTYPE WHERE PLAN_TO_UDFTYPE.EXECUTIONPLAN_HID = 35
DELETE FROM PLAN_TO_UDFTYPE WHERE PLAN_TO_UDFTYPE.EXECUTIONPLAN_HID = 35
DELETE FROM UDFTYPE WHERE UDFTYPE.HID = 12123

SELECT * FROM PLAN_TO_DEPENDENCY;
SELECT * FROM DEPENDENCY;
SELECT PLAN_TO_DEPENDENCY.DEPENDENCY_HID FROM PLAN_TO_DEPENDENCY WHERE PLAN_TO_DEPENDENCY.EXECUTIONPLAN_HID = 35
DELETE FROM PLAN_TO_DEPENDENCY WHERE PLAN_TO_DEPENDENCY.EXECUTIONPLAN_HID = 35

SELECT EXECUTIONPLANITEMTYPE.HID FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.PLAN_HID = 35
SELECT * FROM UDFTYPE
DELETE FROM UDFTYPE WHERE UDFTYPE.PLANITEM_HID = 12313
DELETE FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.HID = 91
SELECT ITEMS_TO_ITEMS.CHILD_HID FROM ITEMS_TO_ITEMS WHERE ITEMS_TO_ITEMS.PARENT_HID = 191
DELETE FROM ITEMS_TO_ITEMS WHERE ITEMS_TO_ITEMS.PARENT_HID = 192
SELECT * FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.HID = 191
SELECT * FROM XREFTYPE
DELETE FROM XREFTYPE WHERE XREFTYPE.TASK_HID = 12
SELECT EXECUTIONPLANITEMTYPE.PROCESSVERSION_HID, EXECUTIONPLANITEMTYPE.SCHEDULEABLEITEM_HID, EXECUTIONPLANITEMTYPE.POINTTYPE_HID FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.HID = 191

SELECT * FROM ORDERLINEIDS;
DELETE FROM ORDERLINEIDS WHERE ORDERLINEIDS.EXECUTIONPLANITEMTYPE_HID = 1231

SELECT * FROM JEOPARDYINFOTYPE;
SELECT * FROM JEOPARDYINFOTYPE_TO_JEOPARDY;
SELECT JEOPARDYINFOTYPE_TO_JEOPARDY.PROCESSJEOPARDYTYPE_HID FROM JEOPARDYINFOTYPE_TO_JEOPARDY WHERE JEOPARDYINFOTYPE_TO_JEOPARDY.JEOPARDYINFOTYPE_HID = 1
DELETE FROM JEOPARDYINFOTYPE_TO_JEOPARDY WHERE JEOPARDYINFOTYPE_TO_JEOPARDY.JEOPARDYINFOTYPE_HID = 1
DELETE FROM JEOPARDYINFOTYPE WHERE JEOPARDYINFOTYPE.HID = 1231
DELETE FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.HID = 35

-- Complete Remove Order
SELECT * FROM ORDER_ WHERE ORDER_.HID = 1 ;
SELECT ORDER_.HEADER_HID, ORDER_.REQUEST_HID FROM ORDER_ WHERE ORDER_.HID = 1
SELECT * FROM HEADER WHERE HEADER.HID = 1
SELECT * FROM FULFILMENTORDER WHERE FULFILMENTORDER.HID = 1
SELECT * FROM ORDER_TO_LINETYPE;
SELECT ORDER_TO_LINETYPE.LINETYPE_HID FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 1
DELETE FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 1
SELECT * FROM LINETYPE WHERE LINETYPE.HID = 1
SELECT * FROM ORDER_TO_FULFILMENTORDER WHERE ORDER_TO_FULFILMENTORDER.ORDER_HID = 1;
SELECT ORDER_TO_FULFILMENTORDER.FULFILMENTORDER_HID FROM ORDER_TO_FULFILMENTORDER WHERE ORDER_TO_FULFILMENTORDER.ORDER_HID = 1
DELETE FROM ORDER_TO_FULFILMENTORDER WHERE ORDER_TO_FULFILMENTORDER.ORDER_HID = 1
DELETE FROM ORDER_ WHERE ORDER_.HID = 1

SELECT LINETYPE.ORDERLINE_HID FROM LINETYPE WHERE LINETYPE.HID = 1
SELECT * FROM ORDERLINE WHERE ;
SELECT * FROM ORDERLINE WHERE ORDERLINE.HID = 2
SELECT ORDERLINE.DELIVERYADDRESS_HID FROM ORDERLINE WHERE ORDERLINE.HID = 2
SELECT ORDERLINE_TO_UDFTYPE.UDFTYPE_HID FROM ORDERLINE_TO_UDFTYPE WHERE ORDERLINE_TO_UDFTYPE.ORDERLINE_HID = 2
DELETE FROM ORDERLINE_TO_UDFTYPE WHERE ORDERLINE_TO_UDFTYPE.ORDERLINE_HID = 2
SELECT ORDERLINE_TO_SLATYPE.SLATYPE_HID FROM ORDERLINE_TO_SLATYPE WHERE ORDERLINE_TO_SLATYPE.ORDERLINE_HID = 2
DELETE FROM ORDERLINE_TO_SLATYPE WHERE ORDERLINE_TO_SLATYPE.ORDERLINE_HID = 2
SELECT ORDERLINE_TO_CTYPE.CHARACTERISTICTYPE_HID FROM ORDERLINE_TO_CTYPE WHERE ORDERLINE_TO_CTYPE.ORDERLINE_HID = 2
DELETE FROM ORDERLINE_TO_CTYPE WHERE ORDERLINE_TO_CTYPE.ORDERLINE_HID = 2
DELETE FROM ORDERLINE WHERE ORDERLINE.HID = 2

SELECT * FROM CHARACTERISTICTYPE;
DELETE FROM CHARACTERISTICTYPE WHERE CHARACTERISTICTYPE.HID = 1
SELECT CTYPE_TO_CVALUETYPE.CHARACTERISTICVALUETYPE_HID FROM CTYPE_TO_CVALUETYPE WHERE CTYPE_TO_CVALUETYPE.CHARACTERISTICTYPE_HID = 1
DELETE FROM CTYPE_TO_CVALUETYPE WHERE CTYPE_TO_CVALUETYPE.CHARACTERISTICTYPE_HID = 1
SELECT * FROM CHARACTERISTICVALUETYPE
DELETE FROM CHARACTERISTICVALUETYPE WHERE CHARACTERISTICVALUETYPE.HID = 1
SELECT * FROM SLATYPE
DELETE FROM SLATYPE WHERE SLATYPE.HID = 1

SELECT * FROM GEOGRAPHICADDRESSTYPE
DELETE FROM GEOGRAPHICADDRESSTYPE WHERE GEOGRAPHICADDRESSTYPE.HID = 1

SELECT * FROM FULFILMENTORDER;
SELECT FULFILMENTORDER.FULFILMENTPROC_HID, FULFILMENTORDER.ORDERHEADER_HID FROM FULFILMENTORDER WHERE FULFILMENTORDER.HID  = 1
SELECT FORDER_TO_ORDERLINE.ORDERLINE_HID FROM FORDER_TO_ORDERLINE WHERE FORDER_TO_ORDERLINE.FULFILMENTORDER_HID = 1
DELETE FROM FORDER_TO_ORDERLINE WHERE FORDER_TO_ORDERLINE.FULFILMENTORDER_HID = 1
SELECT * FROM ADVISORYSTRINGTYPE WHERE ADVISORYSTRINGTYPE.FULFILMENTORDER_HID = 1;
DELETE FROM ADVISORYSTRINGTYPE WHERE ADVISORYSTRINGTYPE.FULFILMENTORDER_HID = 1
DELETE FROM FULFILMENTORDER WHERE FULFILMENTORDER.HID = 1
SELECT * FROM ORDERHEADER WHERE ORDERHEADER.HID = 2
SELECT ORDERHEADER.DELIVERYADDRESS_HID, ORDERHEADER.INVOICEADDRESS_HID FROM ORDERHEADER WHERE ORDERHEADER.HID = 2
SELECT ORDERHEADER_TO_SLATYPE.SLATYPE_HID FROM ORDERHEADER_TO_SLATYPE WHERE ORDERHEADER_TO_SLATYPE.ORDERHEADER_HID = 2
DELETE FROM ORDERHEADER_TO_SLATYPE WHERE ORDERHEADER_TO_SLATYPE.ORDERHEADER_HID = 2
SELECT ORDERHEADER_TO_UDFTYPE.UDFTYPE_HID FROM ORDERHEADER_TO_UDFTYPE WHERE ORDERHEADER_TO_UDFTYPE.ORDERHEADER_HID = 2;
DELETE FROM ORDERHEADER_TO_UDFTYPE WHERE ORDERHEADER_TO_UDFTYPE.ORDERHEADER_HID = 2

SELECT * FROM HEADER WHERE HEADER.HID = 1
SELECT HEADER.ORDERHEADER_HID FROM HEADER WHERE HEADER.HID = 1
DELETE FROM HEADER WHERE HEADER.HID = 1

DELETE FROM ORDERHEADER WHERE ORDERHEADER.HID = 2
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME LIKE 'FKD%'


SELECT ORDERHEADER.ORDERREF FROM ORDERHEADER INNER JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID 
WHERE (ORDERHEADER.ORDERREF='order0' or ORDERHEADER.ORDERREF='order1' or ORDERHEADER.ORDERREF='order2');

-- SQL LEFT JOIN
SELECT ORDERHEADER.CUSTOMERREF, ORDERHEADER.ORDERREF, HEADER.STATUS HEADER_STATUS, HEADER.HID HEADER_HID 
FROM ORDERHEADER LEFT JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID 
ORDER BY HEADER_HID DESC;

-- SQL RIGHT JOIN
SELECT ORDERHEADER.CUSTOMERREF, ORDERHEADER.ORDERREF, HEADER.STATUS HEADER_STATUS, HEADER.HID HEADER_HID 
FROM ORDERHEADER RIGHT JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID 
ORDER BY HEADER_HID DESC;

-- SQL FULL JOIN
SELECT ORDERHEADER.CUSTOMERREF, ORDERHEADER.ORDERREF, HEADER.STATUS HEADER_STATUS, HEADER.HID HEADER_HID 
FROM ORDERHEADER FULL JOIN HEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID 
ORDER BY HEADER_HID DESC;



SELECT * FROM EXECUTIONPLAN;
SELECT EXECUTIONPLAN.UNIQUEID FROM EXECUTIONPLAN
SELECT EXECUTIONPLAN.UNIQUEID FROM EXECUTIONPLAN WHERE (EXECUTIONPLAN.UNIQUEID LIKE '%') AND (EXECUTIONPLAN.STATUSCHANGED < to_date('2011-12-14 07:31:00', 'yyyy-mm-dd hh24:mi:ss'));
SELECT EXECUTIONPLAN.UNIQUEID FROM EXECUTIONPLAN WHERE (EXECUTIONPLAN.UNIQUEID = 'ep2' OR EXECUTIONPLAN.UNIQUEID = 'ep1' OR EXECUTIONPLAN.UNIQUEID LIKE 'ep%') AND (EXECUTIONPLAN.STATUS = 'COMPLETE' OR EXECUTIONPLAN.STATUS = 'TEMPLATE' OR EXECUTIONPLAN.STATUS = 'DRAFT') AND (EXECUTIONPLAN.STATUSCHANGED < to_date('2011-12-14 07:31:00', 'yyyy-mm-dd hh24:mi:ss'));

SELECT * FROM COMPONENT;
SELECT COMPONENT.UNIQUEID FROM COMPONENT;
SELECT COMPONENT.UNIQUEID FROM COMPONENT WHERE (COMPONENT.UNIQUEID = 'PROC1' OR COMPONENT.UNIQUEID LIKE 'PR%');
SELECT COMPONENT.UNIQUEID FROM COMPONENT WHERE (COMPONENT.UNIQUEID = 'PROC1' OR COMPONENT.UNIQUEID LIKE 'PR%') AND (COMPONENT.CREATEDDATE < to_date('2011-12-14 07:31:00', 'yyyy-mm-dd hh24:mi:ss'));


select t.*, t.rowid from order_ t order by hid desc;
select t.*, t.rowid from header t order by hid desc;  --have planuniqueid
select t.*, t.rowid from orderheader t 
--where t.orderref like '%IT3OR%'
order by hid desc ;--have orderRef

--select t.*, t.rowid from fulfilmentorder t order by t.hid desc
select * from executionplan

select * from user_constraints where constraint_name='FKF4F4E9EE95C53CDA'

select * from user_constraints where constraint_name='FK87D2B513255DDFA'

select * from user_constraints where constraint_name='ORDERLINE_TO_UDFTYPE_FK_R'

select * from user_constraints where constraint_name='RBPARAMS_TO_AUDITITEM_FK'

select * from user_constraints where constraint_name='SYS_C0078104'

9
DELETE FROM RESOURCEBUNDLEPARAMS
8
DELETE FROM COMPONENT_TO_OBJECTTYPE
7
DELETE FROM COMPONENTUSERS
6
DELETE FROM COMPONENTGROUPS
5
delete from executionplanitemtype

4
DELETE FROM ORDERLINEIDS

3
DELETE FROM ITEMS_TO_ITEMS



2
delete from UDFTYPE

1
DELETE FROM ORDERLINE_TO_UDFTYPE

-- New Period
CREATE TABLE JBM_DUAL (DUMMY INTEGER, PRIMARY KEY (DUMMY))
INSERT INTO JBM_DUAL VALUES (1)
SELECT 1 FROM JBM_DUAL

CREATE TABLE JBM_MSG_REF (MESSAGE_ID INTEGER, CHANNEL_ID INTEGER, TRANSACTION_ID INTEGER, STATE CHAR(1), ORD INTEGER, PAGE_ORD INTEGER, DELIVERY_COUNT INTEGER, SCHED_DELIVERY INTEGER, PRIMARY KEY(MESSAGE_ID, CHANNEL_ID))
CREATE INDEX JBM_MSG_REF_TX ON JBM_MSG_REF (TRANSACTION_ID, STATE)
INSERT INTO JBM_MSG_REF (CHANNEL_ID, MESSAGE_ID, TRANSACTION_ID, STATE, ORD, PAGE_ORD, DELIVERY_COUNT, SCHED_DELIVERY) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
DELETE FROM JBM_MSG_REF WHERE MESSAGE_ID=? AND CHANNEL_ID=? AND STATE='C'
UPDATE JBM_MSG_REF SET TRANSACTION_ID=?, STATE='-' WHERE MESSAGE_ID=? AND CHANNEL_ID=? AND STATE='C'
UPDATE JBM_MSG_REF SET PAGE_ORD = ? WHERE MESSAGE_ID=? AND CHANNEL_ID=?
UPDATE JBM_MSG_REF SET STATE='C', TRANSACTION_ID = NULL WHERE TRANSACTION_ID=? AND STATE='+'
DELETE FROM JBM_MSG_REF WHERE TRANSACTION_ID=? AND STATE='-'
DELETE FROM JBM_MSG_REF WHERE TRANSACTION_ID=? AND STATE='+'
UPDATE JBM_MSG_REF SET STATE='C', TRANSACTION_ID = NULL WHERE TRANSACTION_ID=? AND STATE='-'
SELECT MESSAGE_ID, DELIVERY_COUNT, PAGE_ORD, SCHED_DELIVERY FROM JBM_MSG_REF WHERE CHANNEL_ID = ? AND PAGE_ORD BETWEEN ? AND ? ORDER BY PAGE_ORD
SELECT MESSAGE_ID, DELIVERY_COUNT, SCHED_DELIVERY FROM JBM_MSG_REF WHERE STATE = 'C' AND CHANNEL_ID = ? AND PAGE_ORD IS NULL ORDER BY ORD
SELECT MESSAGE_ID, DELIVERY_COUNT, SCHED_DELIVERY FROM JBM_MSG_REF WHERE STATE = 'C' AND CHANNEL_ID = ? ORDER BY ORD
UPDATE JBM_MSG_REF SET PAGE_ORD = NULL WHERE PAGE_ORD BETWEEN ? AND ? AND CHANNEL_ID=?
SELECT MIN(PAGE_ORD), MAX(PAGE_ORD) FROM JBM_MSG_REF WHERE CHANNEL_ID = ?
UPDATE JBM_MSG_REF SET DELIVERY_COUNT = ? WHERE MESSAGE_ID = ? AND CHANNEL_ID = ?
UPDATE JBM_MSG_REF SET CHANNEL_ID = ? WHERE CHANNEL_ID = ?
UPDATE JBM_MSG_REF SET CHANNEL_ID = ? WHERE MESSAGE_ID = ? AND CHANNEL_ID = ?
SELECT MESSAGE_ID, CHANNEL_ID FROM JBM_MSG_REF WHERE TRANSACTION_ID = ? AND STATE = '+' ORDER BY ORD
SELECT MESSAGE_ID, CHANNEL_ID FROM JBM_MSG_REF WHERE TRANSACTION_ID = ? AND STATE = '-' ORDER BY ORD
SELECT DISTINCT(CHANNEL_ID) FROM JBM_MSG_REF

CREATE TABLE JBM_MSG (MESSAGE_ID INTEGER, RELIABLE CHAR(1), EXPIRATION INTEGER, TIMESTAMP INTEGER, PRIORITY INTEGER, TYPE INTEGER, HEADERS BLOB, PAYLOAD BLOB, PRIMARY KEY (MESSAGE_ID))
INSERT INTO JBM_MSG (MESSAGE_ID, RELIABLE, EXPIRATION, TIMESTAMP, PRIORITY, TYPE, HEADERS, PAYLOAD) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
INSERT INTO JBM_MSG (MESSAGE_ID, RELIABLE, EXPIRATION, TIMESTAMP, PRIORITY, TYPE) SELECT ?, ?, ?, ?, ?, ? FROM JBM_DUAL WHERE NOT EXISTS (SELECT MESSAGE_ID FROM JBM_MSG WHERE MESSAGE_ID = ?)
UPDATE JBM_MSG SET HEADERS=?, PAYLOAD=? WHERE MESSAGE_ID=?
INSERT INTO JBM_MSG (MESSAGE_ID, RELIABLE, EXPIRATION, TIMESTAMP, PRIORITY, TYPE, HEADERS, PAYLOAD) SELECT ?, ?, ?, ?, ?, ?, ?, ? FROM JBM_DUAL WHERE NOT EXISTS (SELECT MESSAGE_ID FROM JBM_MSG WHERE MESSAGE_ID = ?)
DELETE FROM JBM_MSG WHERE MESSAGE_ID = ? AND NOT EXISTS (SELECT JBM_MSG_REF.MESSAGE_ID FROM JBM_MSG_REF WHERE JBM_MSG_REF.MESSAGE_ID = ?)
SELECT MESSAGE_ID, RELIABLE, EXPIRATION, TIMESTAMP, PRIORITY, HEADERS, PAYLOAD, TYPE FROM JBM_MSG

CREATE TABLE JBM_TX (NODE_ID INTEGER, TRANSACTION_ID INTEGER, BRANCH_QUAL RAW(254), FORMAT_ID INTEGER, GLOBAL_TXID RAW(254), PRIMARY KEY (TRANSACTION_ID))
INSERT INTO JBM_TX (NODE_ID, TRANSACTION_ID, BRANCH_QUAL, FORMAT_ID, GLOBAL_TXID) VALUES(?, ?, ?, ?, ?)
DELETE FROM JBM_TX WHERE NODE_ID = ? AND TRANSACTION_ID = ?
SELECT TRANSACTION_ID, BRANCH_QUAL, FORMAT_ID, GLOBAL_TXID FROM JBM_TX WHERE NODE_ID = ?
UPDATE JBM_TX SET NODE_ID=? WHERE NODE_ID=?

CREATE TABLE JBM_COUNTER (NAME VARCHAR2(255), NEXT_ID INTEGER, PRIMARY KEY(NAME))
UPDATE JBM_COUNTER SET NEXT_ID = ? WHERE NAME=?
SELECT NEXT_ID FROM JBM_COUNTER WHERE NAME=? FOR UPDATE
INSERT INTO JBM_COUNTER (NAME, NEXT_ID) VALUES (?, ?)

CREATE TABLE JBM_ID_CACHE (NODE_ID INTEGER, CNTR INTEGER, JBM_ID VARCHAR2(255), PRIMARY KEY(NODE_ID, CNTR))
UPDATE JBM_ID_CACHE SET JBM_ID = ? WHERE NODE_ID = ? AND CNTR = ?
INSERT INTO JBM_ID_CACHE (NODE_ID, CNTR, JBM_ID) VALUES (?, ?, ?)
SELECT CNTR, JBM_ID FROM JBM_ID_CACHE WHERE NODE_ID = ?

SELECT 1 FROM JBM_DUAL;
SELECT * FROM JBM_POSTOFFICE;
----------------- IPC-496 START --------------------
DELETE FROM MILESTONETYPE_PROPERTY;
DELETE FROM FSYSTEMTYPE_PROPERTY;
DELETE FROM MILESTONETYPE_PROPERTY;
DELETE FROM PROCESSVERSION_TO_MILESTONE;
DELETE FROM PROCESSVERSION_TO_SECTION;
DELETE FROM PROPERTY;
DELETE FROM PROCESS;
DELETE FROM PROCESSVERSION;
DELETE FROM PROCESSSECTIONTYPE;
DELETE FROM FULFILMENTPROC;
DELETE FROM FULFILMENTSYSTEMTYPE;
DELETE FROM MILESTONETYPE;
DELETE FROM POINTTYPE;
DELETE FROM SCHEDULEABLEITEM;

SELECT * FROM IPC_PO_GEN;
UPDATE IPC_PO_GEN SET KEYVALUE = 1 WHERE KEYNAME = 'Process_gen';
SELECT * FROM PROCESS;
SELECT * FROM OBJECTTYPE;
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SYS_C00592892';
----------------- IPC-496 END --------------------

----------------- IPC-497 START --------------------
SELECT * FROM EXECUTIONPLAN; 
SELECT * FROM COMPONENT;
SELECT * FROM PROCESS;
SELECT * FROM OBJECTTYPE;
SELECT * FROM AUDITITEM;

----------------- IPC-497 END --------------------

----------------- IPC-468 START --------------------
SELECT * FROM AUDITITEM;

----------------- IPC-468 END --------------------