drop index order_to_fulfilmentorder_index;
drop index order_to_linetype_index;
drop index forder_to_orderline_index;
drop index fsystemtype_property_index;
drop index orderheader_to_slatype_index;
drop index orderheader_to_udftype_index;
drop index orderline_to_ctype_index;
drop index orderline_to_slatype_index;
drop index orderline_to_udftype_index;
drop index fulfilmentproc_field_index;
drop index ctype_to_cvaluetype_index;
drop INDEX COMPONENTHID_INDEX;
drop INDEX RESOURCETYPE_SCHEITEM_HID ;
drop index component_to_objecttype_index ;
drop index items_to_items_index ;
drop index jeopardy_to_jeopardy_index ;
drop index jeopardysupertype_to_def_index ;
drop index milestonetype_field_index ;
drop index milestonetype_property_index;
drop index plan_to_dependency_index ;
drop index plan_to_udftype_index ;
drop index process_to_milestone_index ;
drop index process_to_section_index ;
drop index subjectdef_to_property_index ;
drop index subject_to_expdependency_index ;
drop index subject_to_impdependency_index ;
-- Order Referred -------------------------------------------------------------------------------------------------
create index order_to_forder_order_index on order_to_fulfilmentorder(order_hid);
create index order_to_forder_forder_index on order_to_fulfilmentorder(fulfilmentorder_hid);
create index order_to_ltype_order_index on order_to_linetype(order_hid);  
create index order_to_ltype_ltype_index on order_to_linetype(linetype_hid); 
create index forder_to_oline_forder_index on forder_to_orderline(fulfilmentorder_hid);
create index forder_to_oline_oline_index on forder_to_orderline(orderline_hid);
create index fstype_property_fstype_index on fsystemtype_property(fulfilmentsystemtype_hid);
create index fstype_property_property_index on fsystemtype_property(property_hid);
create index oheader_stype_oheader_index on orderheader_to_slatype(orderheader_hid);
create index oheader_stype_stype_index on orderheader_to_slatype(slatype_hid);
create index oheader_utype_oheader_index on orderheader_to_udftype(orderheader_hid);
create index oheader_utype_utype_index on orderheader_to_udftype(udftype_hid);
create index oline_to_ctype_oline_index on orderline_to_ctype(orderline_hid);
create index oline_to_ctype_ctype_index on orderline_to_ctype(characteristictype_hid);
create index oline_to_slatype_oline_index on orderline_to_slatype(orderline_hid);
create index oline_to_slatype_slatype_index on orderline_to_slatype(slatype_hid);
create index oline_to_udftype_oline_index on orderline_to_udftype(orderline_hid);
create index oline_to_udftype_udftype_index on orderline_to_udftype(udftype_hid);
create index fproc_field_fproc_index on fulfilmentproc_field(fulfilmentproc_hid);
create index fproc_field_field_index on fulfilmentproc_field(field_hid);
create index ctype_to_cvtype_ctype_index on ctype_to_cvaluetype(characteristictype_hid);
create index ctype_to_cvtype_cvtype_index on ctype_to_cvaluetype(characteristicvaluetype_hid);
create index oline_geoaddr_index on orderline(DELIVERYADDRESS_HID);
create index ltype_oline_index on linetype(ORDERLINE_HID);
create index order_header_index on order_(HEADER_HID);
create index order_forder_index on order_(REQUEST_HID);
create index header_oheader_index on header(ORDERHEADER_HID);
create index forder_oheader_index on fulfilmentorder(ORDERHEADER_HID);
create index forder_fproc_index on fulfilmentorder(FULFILMENTPROC_HID);
create index fproc_pstype_index on fulfilmentproc(FULFILMENTSYSTEMTYPE_HID);
create index oheader_geoaddr_del_index on orderheader(DELIVERYADDRESS_HID);
create index oheader_geoaddr_inv_index on orderheader(INVOICEADDRESS_HID);
create index advisorystringtype_index on advisorystringtype(FULFILMENTORDER_HID);
-- Plan Referred ------------------------------------------------------------------------------------------------
create index items_to_items_p_index on items_to_items(parent_hid);
create index items_to_items_c_index on items_to_items(child_hid);
create index pjeo_to_jeo_jeo_index on jeopardyinfotype_to_jeopardy(jeopardyinfotype_hid);
create index pjeo_to_jeo_pjeo_index on jeopardyinfotype_to_jeopardy(processjeopardytype_hid);
create index jeost_to_def_def_index on jeopardysupertype_to_def(jeopardydeftype_hid);
create index jeost_to_def_jeost_index on jeopardysupertype_to_def(jeopardysupertype_hid);
create index milestone_field_m_index on milestonetype_field(milestonetype_hid);
create index milestone_field_f_index on milestonetype_field(field_hid);
create index milestone_property_m_index on milestonetype_property(milestonetype_hid);
create index milestone_property_p_index on milestonetype_property(property_hid);
create index plan_to_dep_plan_index on plan_to_dependency(executionplan_hid);
create index plan_to_dep_dep_index on plan_to_dependency(dependency_hid);
create index plan_to_udftype_p_index on plan_to_udftype(executionplan_hid);
create index plan_to_udftype_u_index on plan_to_udftype(udftype_hid);
create index pv_to_milestone_p_index on processversion_to_milestone(processversion_hid);
create index pv_to_milestone_v_index on processversion_to_milestone(milestone_hid);
create index pv_to_section_p_index on processversion_to_section(processversion_hid);
create index pv_to_section_s_index on processversion_to_section(processsectiontype_hid);
create index resourcetype_scheitem_index on resourcetype(scheduleableitem_hid);
create index orderlineids_item_index on orderlineids(executionplanitemtype_hid);
create index xreftype_item_index on xreftype(task_hid);
create index udftype_item_index on udftype(planitem_hid);
create index item_processversion_index on executionplanitemtype(processversion_hid);
create index item_plan_index on executionplanitemtype(plan_hid);
create index item_pointtype_index on executionplanitemtype(pointtype_hid);
create index item_scheduleableitem on executionplanitemtype(scheduleableitem_hid);
create index pv_endmilstone_index on processversion(endmilestone_hid);
create index pv_startmilstone_index on processversion(startmilestone_hid);
create index pv_fulfilmentproc_index on processversion(fulfilmentproc_hid);
create index pv_scheduleableitem_index on processversion(scheduleableitem_hid);
create index pv_taskcancellmilestone_index on processversion(taskcancelledmilestone_hid);
create index milestone_pointtype_index on milestonetype(pointtype_hid);
create index plan_fulfilmentproc_index on executionplan(fulfilmentproc_hid);
create index plan_jeopardyinfo_index on executionplan(jeopardyinfotype_hid);
create index dependency_pointtype_index on dependency(pointtype_hid);
create index dependency_exter_index on dependency(externaldependencytype_hid);
create index dependency_start_index on dependency(starttimedependencytype_hid);
create index dependency_plan_index on dependency(planitemdependencytype_hid);
create index exter_fulsystemtype_index on externaldependencytype(fulfilmentsystemtype_hid);
create index start_jeopardysuper_index on starttimedependencytype(jeopardysupertype_hid);
create index actions_jeo_index on actions(jeopardydeftype_hid);
create index processsectiontype_sche_index on processsectiontype(scheduleableitem_hid);
--- Component Referred ---------------------------------------------------------------------------------------------
create index comp_to_otype_comp_index on component_to_objecttype(COMPONENT_HID);
create index comp_to_otype_otype_index on component_to_objecttype(objecttype_hid);
create index componentgroups_comp_index on componentgroups(component_hid);
create index componentusers_comp_index on componentusers(component_hid);
create index process_pv_index on process(processversion_hid);
-- OrchSubject Referred ---------------------------------------------------------------------------------------------
create index subdef_to_property_s_index on subjectdef_to_property(subjectdef_hid);
create index subdef_to_property_p_index on subjectdef_to_property(property_hid);
create index subject_to_expdep_s_index on subject_to_expdependency(orchsubject_hid);
create index subject_to_expdep_d_index on subject_to_expdependency(dependency_hid);
create index subject_to_impdep_s__index on subject_to_impdependency(orchsubject_hid);
create index subject_to_impdep_i_index on subject_to_impdependency(dependency_hid);
create index subject_observers_index on subject_observers(subject_hid);
---------------------------------------------------------------------------------------------------------------------