-- remove foreign key constraint
-- ExecutionPlan Start--
alter table EXECUTIONPLAN drop constraint PLAN_TO_FULFILMENTPROC_FK;
alter table EXECUTIONPLAN drop constraint PLAN_TO_JEOPARDYINFOTYPE_FK; 

alter table FULFILMENTPROC drop constraint FPROC_TO_FSYSTEMTYPE_FK;

alter table PLAN_TO_UDFTYPE drop constraint PLAN_TO_UDFTYPE_FK_R;
alter table PLAN_TO_UDFTYPE drop constraint PLAN_TO_UDFTYPE_FK;

alter table PLAN_TO_DEPENDENCY drop constraint PLAN_TO_DEPENDENCY_FK;
alter table PLAN_TO_DEPENDENCY drop constraint PLAN_TO_DEPENDENCY_FK_R;

alter table DEPENDENCY drop constraint POINTTYPE_TO_DEPENDENCY_FK;
alter table DEPENDENCY drop constraint DEPENDENCY_TO_PLANITEM_FK;
alter table DEPENDENCY drop constraint DEPENDENCY_TO_STARTTIME_FK;
alter table DEPENDENCY drop constraint DEPENDENCY_TO_EXTERNAL_FK; 

alter table EXTERNALDEPENDENCYTYPE drop constraint EXTERNALD_TO_FSYSTEMTYPE_FK;

alter table FSYSTEMTYPE_PROPERTY drop constraint FULFS_TO_PROPERTY_FK;
alter table FSYSTEMTYPE_PROPERTY drop constraint FULFS_TO_PROPERTY_FK_R;

alter table STARTTIMEDEPENDENCYTYPE drop constraint STARTTIME_TO_JEOPARDYSUPER_FK;

alter table JEOPARDYSUPERTYPE_TO_DEF drop constraint JEOPARDYSUPERTYPE_TO_DEF_FK_R;
alter table JEOPARDYSUPERTYPE_TO_DEF drop constraint JEOPARDYSUPERTYPE_TO_DEF_FK;

alter table ACTIONS drop constraint ACTIONS_TO_JEOPARDYDEFTYPE_FK;

alter table JEOPARDYINFOTYPE_TO_JEOPARDY drop constraint JEOPARDYINFO_TO_JEOPARDY_FK;
alter table JEOPARDYINFOTYPE_TO_JEOPARDY drop constraint JEOPARDYINFO_TO_JEOPARDY_FK_R;

alter table PROCESSJEOPARDYTYPE drop constraint PJEOPARDY_TO_CONTINGENCY_FK;
alter table PROCESSJEOPARDYTYPE drop constraint PJEOPARDY_TO_MONITORING_FK ;
alter table PROCESSJEOPARDYTYPE drop constraint PROCESSJEOPARDY_TO_MAXIMUM_FK ;
alter table PROCESSJEOPARDYTYPE drop constraint PROCESSJEOPARDY_TO_TYPICAL_FK ;
alter table PROCESSJEOPARDYTYPE drop constraint PROCESSJEOPARDY_TO_MHSB_FK ;
alter table PROCESSJEOPARDYTYPE drop constraint PJEOPARDY_TO_REPORTING_FK;
alter table PROCESSJEOPARDYTYPE drop constraint PROCESSJEOPARDY_TO_ENDDATE_FK ;
alter table PROCESSJEOPARDYTYPE drop constraint PROCESSJEOPARDY_TO_MSO_FK ;
alter table PROCESSJEOPARDYTYPE drop constraint PROCSTYPE_TO_PROCJTYPE_FK ;

alter table FULFILMENTPROC_FIELD drop constraint FPROC_TO_FIELD_FK ;
alter table FULFILMENTPROC_FIELD drop constraint FPROC_TO_FIELD_FK_R ;

alter table EXECUTIONPLANITEMTYPE drop constraint TASK_TO_PROCESSVERSION_FK ;
alter table EXECUTIONPLANITEMTYPE drop constraint PLANITEM_TO_POINTTYPE_FK ;
alter table EXECUTIONPLANITEMTYPE drop constraint PLAN_TO_PLANITEM_FK ;
alter table EXECUTIONPLANITEMTYPE drop constraint PLANITEM_SCHEDULEABLE_FK ;

alter table RESOURCETYPE drop constraint SITEM_TO_RESOURCETYPE_FK;

alter table UDFTYPE drop constraint PLANITEM_TO_UDFTYPE_FK;

alter table ORDERLINEIDS drop constraint ORDERLINEID_TO_PLANITEM_FK;

alter table XREFTYPE drop constraint XREFTYPE_TO_TASK_FK;

alter table ITEMS_TO_ITEMS drop constraint ITEMS_TO_ITEMS_FK_R ;
alter table ITEMS_TO_ITEMS drop constraint ITEMS_TO_ITEMS_FK ;

alter table PROCESSVERSION drop constraint PROCESS_TASKCANCELLEDMS_FK ;
alter table PROCESSVERSION drop constraint PROCESS_ENDMILESTONE_FK ;
alter table PROCESSVERSION drop constraint PROCESS_TO_FULFILMENTPROC_FK ;
alter table PROCESSVERSION drop constraint PROCESS_STARTMILESTONE_FK ;
alter table PROCESSVERSION drop constraint PROCESS_SCHEDULEABLEITEM_FK ;

alter table PROCESSSECTIONTYPE drop constraint PROCTYPE_TO_SITEM_FK;

alter table MILESTONETYPE drop constraint MILESTONETYPE_TO_POINTTYPE_FK;

alter table MILESTONETYPE_FIELD drop constraint MILESTONE_TO_FIELD_FK ;
alter table MILESTONETYPE_FIELD drop constraint MILESTONE_TO_FIELD_FK_R ;

alter table COMPONENT_TO_OBJECTTYPE drop constraint COMPONENT_TO_OBJECTTYPE_FK_R ;
alter table COMPONENT_TO_OBJECTTYPE drop constraint COMPONENT_TO_OBJECTTYPE_FK ;

alter table COMPONENTGROUPS drop constraint CGROUPS_TO_COMPONENT_FK ;
alter table COMPONENTUSERS drop constraint COMPONENTUSERS_TO_COMPONENT_FK ;

alter table PROCESS drop constraint PROCESS_TO_PROCESSVERSION_FK ;

alter table ORDER_ drop constraint ORDER_TO_HEADER_FK ;
alter table ORDER_ drop constraint ORDER_TO_REQUEST_FK ;

alter table HEADER drop constraint HEADER_TO_ORDERHEADER_FK ;

alter table ORDERHEADER drop constraint ORDERHEADER_INVOICEADDRESS_FK ;
alter table ORDERHEADER drop constraint ORDERHEADER_DELIVERYADDRESS_FK ;

alter table ORDERHEADER_TO_UDFTYPE drop constraint ORDERHEADER_TO_UDFTYPE_FK_R ;
alter table ORDERHEADER_TO_UDFTYPE drop constraint ORDERHEADER_TO_UDFTYPE_FK ;

alter table ORDER_TO_LINETYPE drop constraint ORDER_TO_LINETYPE_FK_R ;
alter table ORDER_TO_LINETYPE drop constraint ORDER_TO_LINETYPE_FK ;

alter table FULFILMENTORDER drop constraint FORDER_TO_FULFILMENTPROC_FK ;
alter table FULFILMENTORDER drop constraint FORDER_TO_ORDERHEADER_FK ;

alter table ORDERHEADER_TO_SLATYPE drop constraint ORDERHEADER_TO_SLATYPE_FK_R ;
alter table ORDERHEADER_TO_SLATYPE drop constraint ORDERHEADER_TO_SLATYPE_FK ;

alter table ADVISORYSTRINGTYPE drop constraint ADVISORYSTRING_TO_FORDER_FK;

alter table FORDER_TO_ORDERLINE drop constraint FORDER_TO_ORDERLINE_FK ;
alter table FORDER_TO_ORDERLINE drop constraint FORDER_TO_ORDERLINE_FK_R ;

alter table ORDER_TO_FULFILMENTORDER drop constraint ORDER_TO_FULFILMENTORDER_FK_R ;
alter table ORDER_TO_FULFILMENTORDER drop constraint ORDER_TO_FULFILMENTORDER_FK ;

alter table LINETYPE drop constraint LINE_TO_ORDERLINE_FK ;

alter table ORDERLINE drop constraint ORDERLINE_DELIVERYADDRESS_FK ;

alter table ORDERLINE_TO_SLATYPE drop constraint ORDERLINE_TO_SLATYPE_FK_R ;
alter table ORDERLINE_TO_SLATYPE drop constraint ORDERLINE_TO_SLATYPE_FK ;
alter table ORDERLINE_TO_UDFTYPE drop constraint ORDERLINE_TO_UDFTYPE_FK_R ;
alter table ORDERLINE_TO_UDFTYPE drop constraint ORDERLINE_TO_UDFTYPE_FK ;
alter table ORDERLINE_TO_CTYPE drop constraint ORDERLINE_TO_CTYPE_FK_R ;
alter table ORDERLINE_TO_CTYPE drop constraint ORDERLINE_TO_CTYPE_FK ;
alter table CTYPE_TO_CVALUETYPE drop constraint CTYPE_TO_CVALUETYPE_FK_R;
alter table CTYPE_TO_CVALUETYPE drop constraint CTYPE_TO_CVALUETYPE_FK;

alter table SUBJECT_TO_EXPDEPENDENCY drop constraint SUBJECT_TO_EXPDEPENDENCY_FK_R; 
alter table SUBJECT_TO_EXPDEPENDENCY drop constraint SUBJECT_TO_EXPDEPENDENCY_FK;
alter table SUBJECT_TO_IMPDEPENDENCY drop constraint SUBJECT_TO_IMPDEPENDENCY_FK_R;
alter table SUBJECT_TO_IMPDEPENDENCY drop constraint SUBJECT_TO_IMPDEPENDENCY_FK;
alter table SUBJECT_OBSERVERS drop constraint OBSERVERS_TO_SUBJECT_FK;
alter table SUBJECTDEF_TO_PROPERTY drop constraint SUBJECTDEF_TO_PROPERTY_FK_R;
alter table SUBJECTDEF_TO_PROPERTY drop constraint SUBJECTDEF_TO_PROPERTY_FK;

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_FULFILMENTPROC_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_JEOPARDYINFOTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FPROC_TO_FSYSTEMTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_UDFTYPE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_UDFTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_DEPENDENCY_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_DEPENDENCY_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'POINTTYPE_TO_DEPENDENCY_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'DEPENDENCY_TO_PLANITEM_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'DEPENDENCY_TO_STARTTIME_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'DEPENDENCY_TO_EXTERNAL_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'EXTERNALD_TO_FSYSTEMTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FULFS_TO_PROPERTY_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FULFS_TO_PROPERTY_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'STARTTIME_TO_JEOPARDYSUPER_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'JEOPARDYSUPERTYPE_TO_DEF_FK_R';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'JEOPARDYSUPERTYPE_TO_DEF_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ACTIONS_TO_JEOPARDYDEFTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'JEOPARDYINFO_TO_JEOPARDY_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'JEOPARDYINFO_TO_JEOPARDY_FK_R';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PJEOPARDY_TO_CONTINGENCY_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PJEOPARDY_TO_MONITORING_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESSJEOPARDY_TO_MAXIMUM_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESSJEOPARDY_TO_TYPICAL_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESSJEOPARDY_TO_MHSB_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PJEOPARDY_TO_REPORTING_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESSJEOPARDY_TO_ENDDATE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESSJEOPARDY_TO_MSO_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCSTYPE_TO_PROCJTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FPROC_TO_FIELD_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FPROC_TO_FIELD_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'TASK_TO_PROCESSVERSION_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLANITEM_TO_POINTTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_PLANITEM_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLANITEM_SCHEDULEABLE_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SITEM_TO_RESOURCETYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLANITEM_TO_UDFTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINEID_TO_PLANITEM_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'XREFTYPE_TO_TASK_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ITEMS_TO_ITEMS_FK_R';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ITEMS_TO_ITEMS_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESS_TASKCANCELLEDMS_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESS_ENDMILESTONE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESS_TO_FULFILMENTPROC_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESS_STARTMILESTONE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESS_SCHEDULEABLEITEM_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCTYPE_TO_SITEM_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'MILESTONETYPE_TO_POINTTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'MILESTONE_TO_FIELD_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'MILESTONE_TO_FIELD_FK_R';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'COMPONENT_TO_OBJECTTYPE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'COMPONENT_TO_OBJECTTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CGROUPS_TO_COMPONENT_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'COMPONENTUSERS_TO_COMPONENT_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PROCESS_TO_PROCESSVERSION_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDER_TO_HEADER_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDER_TO_REQUEST_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'HEADER_TO_ORDERHEADER_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERHEADER_INVOICEADDRESS_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERHEADER_DELIVERYADDRESS_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERHEADER_TO_UDFTYPE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERHEADER_TO_UDFTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDER_TO_LINETYPE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDER_TO_LINETYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FORDER_TO_FULFILMENTPROC_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FORDER_TO_ORDERHEADER_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERHEADER_TO_SLATYPE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERHEADER_TO_SLATYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ADVISORYSTRING_TO_FORDER_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FORDER_TO_ORDERLINE_FK';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FORDER_TO_ORDERLINE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDER_TO_FULFILMENTORDER_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDER_TO_FULFILMENTORDER_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'LINE_TO_ORDERLINE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINE_DELIVERYADDRESS_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINE_TO_SLATYPE_FK_R';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINE_TO_SLATYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINE_TO_UDFTYPE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINE_TO_UDFTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINE_TO_CTYPE_FK_R';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'ORDERLINE_TO_CTYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CTYPE_TO_CVALUETYPE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CTYPE_TO_CVALUETYPE_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SUBJECT_TO_EXPDEPENDENCY_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SUBJECT_TO_EXPDEPENDENCY_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SUBJECT_TO_IMPDEPENDENCY_FK_R';

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SUBJECT_TO_IMPDEPENDENCY_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'OBSERVERS_TO_SUBJECT_FK';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SUBJECTDEF_TO_PROPERTY_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SUBJECTDEF_TO_PROPERTY_FK';

-- ExecutionPlan End--

--order
SELECT * FROM ORDERLINE_TO_SLATYPE;
INSERT INTO ORDERLINE_TO_SLATYPE VALUES(1,1);

SELECT * FROM ORDERLINE_TO_UDFTYPE;
INSERT INTO ORDERLINE_TO_UDFTYPE VALUES(1,1);

SELECT * FROM GEOGRAPHICADDRESSTYPE;

SELECT * FROM ORDERLINE;
INSERT INTO ORDERLINE VALUES(1,'uom','customerItemId',1,'lineNumber','notes','orderLineAction','productId',1,sysdate,1);

SELECT * FROM LINETYPE;
INSERT INTO LINETYPE VALUES(1,1,'status',sysdate,1);

SELECT * FROM ORDER_TO_FULFILMENTORDER;
INSERT INTO ORDER_TO_FULFILMENTORDER VALUES (1,1);

SELECT * FROM FORDER_TO_ORDERLINE;
INSERT INTO FORDER_TO_ORDERLINE VALUES(1,1);

SELECT * FROM ADVISORYSTRINGTYPE;
INSERT INTO ADVISORYSTRINGTYPE VALUES(1,'advice');

SELECT * FROM FULFILMENTORDER;
INSERT INTO FULFILMENTORDER VALUES(1,'originator',sysdate,1,1,1,1);

SELECT * FROM ORDER_TO_LINETYPE;
INSERT INTO ORDER_TO_LINETYPE VALUES(1,1);

SELECT * FROM SLATYPE;
INSERT INTO SLATYPE VALUES(1,1,'id');

SELECT * FROM ORDERHEADER_TO_SLATYPE;
INSERT INTO ORDERHEADER_TO_SLATYPE VALUES(1,1);

SELECT * FROM ORDERHEADER_TO_UDFTYPE;
INSERT INTO ORDERHEADER_TO_UDFTYPE VALUES(1,1);

SELECT * FROM GEOGRAPHICADDRESSTYPE;
INSERT INTO GEOGRAPHICADDRESSTYPE VALUES(1,'country',1,'stateOrProvince','supplementaryLocation','locality','postcode','streetName','streetNr','streetType');

SELECT * FROM ORDERHEADER;
INSERT INTO ORDERHEADER VALUES (1,'IPCTEST',1,'jeopardyDetection','notes','order001',sysdate,1,1);

SELECT * FROM HEADER;
INSERT INTO HEADER VALUES(1,1,'orderPlanStatus','originator','planUniqueId','stateChanger','status',sysdate,1,'warning',1);

SELECT * FROM ORDER_;
INSERT INTO ORDER_ VALUES (1,'pk',1,1,1);

--processComponent
SELECT * FROM PROCESS;
INSERT INTO PROCESS VALUES(1,'pk',1,1);

SELECT * FROM COMPONENTUSERS;
INSERT INTO COMPONENTUSERS VALUSE VALUES(1,'flags','name');

SELECT * FROM COMPONENTGROUPS;
INSERT INTO COMPONENTGROUPS VALUSE VALUES(1,'flags','name');

SELECT * FROM OBJECTTYPE;
INSERT INTO OBJECTTYPE VALUES (1,'desc',1,'id',sysdate,sysdate,sysdate,sysdate);

SELECT * FROM COMPONENT_TO_OBJECTTYPE;
INSERT INTO COMPONENT_TO_OBJECTTYPE VALUES(1,1);

SELECT * FROM COMPONENT;
INSERT INTO COMPONENT VALUES(1,'pk',1,'fucker',sysdate,'desc','type','pc01');

--plan
SELECT * FROM MILESTONETYPE_FIELD;
INSERT INTO MILESTONETYPE_FIELD VALUES(1,1);

SELECT * FROM MILESTONETYPE;
INSERT INTO MILESTONETYPE VALUES(1,'desc',1,'id','status', 1);

SELECT * FROM PROCESSSECTIONTYPE;
INSERT INTO PROCESSSECTIONTYPE VALUES(1,'id',1,'id',1);

SELECT * FROM PROCESSVERSION;
INSERT INTO PROCESSVERSION VALUES(1,1,1,1,1,1,1,1);

SELECT * FROM ITEMS_TO_ITEMS;
INSERT INTO ITEMS_TO_ITEMS VALUES(1,2);

SELECT * FROM XREFTYPE;
INSERT INTO XREFTYPE VALUES(1,'121','121');

SELECT * FROM ORDERLINEIDS;
INSERT INTO ORDERLINEIDS VALUES(1,'1231');

SELECT * FROM UDFTYPE;
INSERT INTO UDFTYPE VALUES(2,1,'name','value',1);

SELECT * FROM RESOURCETYPE;
INSERT INTO RESOURCETYPE VALUES(1,'A',100,1,'reservation','type',1);

SELECT * FROM SCHEDULEABLEITEM;
INSERT INTO SCHEDULEABLEITEM VALUES(1,1000,1,1000,500,1,1500,'800','400',1,'1200');

SELECT * FROM POINTTYPE;
INSERT INTO POINTTYPE VALUES(1,sysdate,1,1000,sysdate);

SELECT * FROM EXECUTIONPLANITEMTYPE;
INSERT INTO EXECUTIONPLANITEMTYPE VALUES ('classType',1,'desc',1,'status',sysdate,'taskid','action','itemId','uniqueCompID','PLANFRAGMENTUNIQUEID',1,1,1,1);

SELECT * FROM FIELD;
INSERT INTO FIELD VALUES(1,1,'IO','name',1,122,'value');

SELECT * FROM FULFILMENTPROC_FIELD;
INSERT INTO FULFILMENTPROC_FIELD VALUES(1,1);

SELECT * FROM PROCESSJEOPARDYTYPE;
INSERT INTO PROCESSJEOPARDYTYPE VALUES(1,1,1,1,1,1,1,1,1,1,1);

SELECT * FROM JEOPARDYINFOTYPE_TO_JEOPARDY;
INSERT INTO JEOPARDYINFOTYPE_TO_JEOPARDY VALUES(1,1);

SELECT * FROM ACTIONS;
INSERT INTO ACTIONS VALUES(1,'asda');

SELECT * FROM JEOPARDYDEFTYPE;
INSERT INTO JEOPARDYDEFTYPE VALUES(1,1,'type');

SELECT * FROM JEOPARDYSUPERTYPE_TO_DEF;
INSERT INTO JEOPARDYSUPERTYPE_TO_DEF VALUES(1,1);

SELECT * FROM JEOPARDYSUPERTYPE;
INSERT INTO JEOPARDYSUPERTYPE VALUES('classtype',1,1,'TYPE',sysdate,'APPLIEDON',1,1,1);

SELECT * FROM STARTTIMEDEPENDENCYTYPE;
INSERT INTO STARTTIMEDEPENDENCYTYPE VALUES(1,'DEPENDENCYID','EVENTID','READY',100,sysdate,1,'type',1)

SELECT * FROM PLANITEMDEPENDENCYTYPE;
INSERT INTO PLANITEMDEPENDENCYTYPE VALUES(1,'DEPENDENCYID','EVENTID','READY',100,1,'MILESTONEID','PLANUNIQUEID','TASKID','type');

SELECT * FROM PROPERTY;
INSERT INTO PROPERTY VALUES(1,1,'1','name','value');

SELECT * FROM FSYSTEMTYPE_PROPERTY;
INSERT INTO FSYSTEMTYPE_PROPERTY VALUES(1,1);

SELECT * FROM FULFILMENTSYSTEMTYPE;
INSERT INTO FULFILMENTSYSTEMTYPE VALUES (1,1,'id');

SELECT * FROM EXTERNALDEPENDENCYTYPE;
INSERT INTO EXTERNALDEPENDENCYTYPE VALUES(1,'DEPENDENCYID','EVENTID','READY',100, sysdate,1,1);

SELECT * FROM DEPENDENCY;
INSERT INTO DEPENDENCY VALUES(1,1,1,1,1,1);

SELECT * FROM PLAN_TO_DEPENDENCY;
INSERT INTO PLAN_TO_DEPENDENCY VALUES(1,1);

SELECT * FROM UDFTYPE;
INSERT INTO UDFTYPE(HID,HVER,NAME_,VALUE_) VALUES(1,1,'name','value');

SELECT * FROM PLAN_TO_UDFTYPE;
INSERT INTO PLAN_TO_UDFTYPE VALUES (1,1);

SELECT * FROM JEOPARDYINFOTYPE;
INSERT INTO JEOPARDYINFOTYPE VALUES(1,100,100,100,100,sysdate,1,'state',1.0, 50,50,50,50,sysdate);

SELECT * FROM FULFILMENTPROC;
INSERT INTO FULFILMENTPROC VALUES(1,'desc',1,'procname',1);

SELECT * FROM EXECUTIONPLAN;
DELETE FROM EXECUTIONPLAN;
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PLAN_TO_FULFILMENTPROC_FK';
INSERT INTO EXECUTIONPLAN VALUES(1,'pk','desc','JEOPARDYDETECTION','MASTERRECORDID','ORIGINATOR',sysdate,sysdate,1,'DRAFT',sysdate,'muep1','waring',1, 1,1);


-- create constraint
alter table EXECUTIONPLAN add constraint PLAN_TO_JEOPARDYINFOTYPE_FK foreign key (JEOPARDYINFOTYPE_HID) references JEOPARDYINFOTYPE;
alter table EXECUTIONPLAN add constraint PLAN_TO_FULFILMENTPROC_FK foreign key (FULFILMENTPROC_HID) references FULFILMENTPROC;

alter table FULFILMENTPROC add constraint FPROC_TO_FSYSTEMTYPE_FK foreign key (FULFILMENTSYSTEMTYPE_HID) references FULFILMENTSYSTEMTYPE;

alter table PLAN_TO_UDFTYPE add constraint PLAN_TO_UDFTYPE_FK_R foreign key (UDFTYPE_HID) references UDFTYPE;
alter table PLAN_TO_UDFTYPE add constraint PLAN_TO_UDFTYPE_FK foreign key (EXECUTIONPLAN_HID) references EXECUTIONPLAN;

alter table PLAN_TO_DEPENDENCY add constraint PLAN_TO_DEPENDENCY_FK foreign key (EXECUTIONPLAN_HID) references EXECUTIONPLAN;
alter table PLAN_TO_DEPENDENCY add constraint PLAN_TO_DEPENDENCY_FK_R foreign key (DEPENDENCY_HID) references DEPENDENCY;

alter table DEPENDENCY add constraint POINTTYPE_TO_DEPENDENCY_FK foreign key (POINTTYPE_HID) references POINTTYPE;
alter table DEPENDENCY add constraint DEPENDENCY_TO_PLANITEM_FK foreign key (PLANITEMDEPENDENCYTYPE_HID) references PLANITEMDEPENDENCYTYPE;
alter table DEPENDENCY add constraint DEPENDENCY_TO_STARTTIME_FK foreign key (STARTTIMEDEPENDENCYTYPE_HID) references STARTTIMEDEPENDENCYTYPE;
alter table DEPENDENCY add constraint DEPENDENCY_TO_EXTERNAL_FK foreign key (EXTERNALDEPENDENCYTYPE_HID) references EXTERNALDEPENDENCYTYPE;
alter table EXTERNALDEPENDENCYTYPE add constraint EXTERNALD_TO_FSYSTEMTYPE_FK foreign key (FULFILMENTSYSTEMTYPE_HID) references FULFILMENTSYSTEMTYPE;

alter table FSYSTEMTYPE_PROPERTY add constraint FULFS_TO_PROPERTY_FK foreign key (FULFILMENTSYSTEMTYPE_HID) references FULFILMENTSYSTEMTYPE;
alter table FSYSTEMTYPE_PROPERTY add constraint FULFS_TO_PROPERTY_FK_R foreign key (PROPERTY_HID) references PROPERTY;

alter table STARTTIMEDEPENDENCYTYPE add constraint STARTTIME_TO_JEOPARDYSUPER_FK foreign key (JEOPARDYSUPERTYPE_HID) references JEOPARDYSUPERTYPE;

alter table JEOPARDYSUPERTYPE_TO_DEF add constraint JEOPARDYSUPERTYPE_TO_DEF_FK_R foreign key (JEOPARDYDEFTYPE_HID) references JEOPARDYDEFTYPE;
alter table JEOPARDYSUPERTYPE_TO_DEF add constraint JEOPARDYSUPERTYPE_TO_DEF_FK foreign key (JEOPARDYSUPERTYPE_HID) references JEOPARDYSUPERTYPE;

alter table ACTIONS add constraint ACTIONS_TO_JEOPARDYDEFTYPE_FK foreign key (JEOPARDYDEFTYPE_HID) references JEOPARDYDEFTYPE;

alter table JEOPARDYINFOTYPE_TO_JEOPARDY add constraint JEOPARDYINFO_TO_JEOPARDY_FK foreign key (JEOPARDYINFOTYPE_HID) references JEOPARDYINFOTYPE;
alter table JEOPARDYINFOTYPE_TO_JEOPARDY add constraint JEOPARDYINFO_TO_JEOPARDY_FK_R foreign key (PROCESSJEOPARDYTYPE_HID) references PROCESSJEOPARDYTYPE;

alter table PROCESSJEOPARDYTYPE add constraint PJEOPARDY_TO_CONTINGENCY_FK foreign key (CONTINGENCY_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PJEOPARDY_TO_MONITORING_FK foreign key (MONITORINGTYPE_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PROCESSJEOPARDY_TO_MAXIMUM_FK foreign key (MAXIMUM_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PROCESSJEOPARDY_TO_TYPICAL_FK foreign key (TYPICAL_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PROCESSJEOPARDY_TO_MHSB_FK foreign key (MUSTHAVESTARTEDBEFORE_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PJEOPARDY_TO_REPORTING_FK foreign key (REPORTING_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PROCESSJEOPARDY_TO_ENDDATE_FK foreign key (ENDDATE_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PROCESSJEOPARDY_TO_MSO_FK foreign key (MUSTSTARTON_HID) references JEOPARDYSUPERTYPE;
alter table PROCESSJEOPARDYTYPE add constraint PROCSTYPE_TO_PROCJTYPE_FK foreign key (PROCESSSECTIONTYPE_HID)  references PROCESSSECTIONTYPE;

alter table FULFILMENTPROC_FIELD add constraint FPROC_TO_FIELD_FK foreign key (FULFILMENTPROC_HID) references FULFILMENTPROC;
alter table FULFILMENTPROC_FIELD add constraint FPROC_TO_FIELD_FK_R foreign key (FIELD_HID) references FIELD;

alter table EXECUTIONPLANITEMTYPE add constraint TASK_TO_PROCESSVERSION_FK foreign key (PROCESSVERSION_HID) references PROCESSVERSION;
alter table EXECUTIONPLANITEMTYPE add constraint PLANITEM_TO_POINTTYPE_FK foreign key (POINTTYPE_HID) references POINTTYPE;
alter table EXECUTIONPLANITEMTYPE add constraint PLAN_TO_PLANITEM_FK foreign key (PLAN_HID) references EXECUTIONPLAN;
alter table EXECUTIONPLANITEMTYPE add constraint PLANITEM_SCHEDULEABLE_FK foreign key (SCHEDULEABLEITEM_HID) references SCHEDULEABLEITEM;

alter table RESOURCETYPE add constraint SITEM_TO_RESOURCETYPE_FK foreign key (SCHEDULEABLEITEM_HID) references SCHEDULEABLEITEM;

alter table UDFTYPE add constraint PLANITEM_TO_UDFTYPE_FK foreign key (PLANITEM_HID) references EXECUTIONPLANITEMTYPE;

alter table ORDERLINEIDS add constraint ORDERLINEID_TO_PLANITEM_FK foreign key (EXECUTIONPLANITEMTYPE_HID) references EXECUTIONPLANITEMTYPE;

alter table XREFTYPE add constraint XREFTYPE_TO_TASK_FK foreign key (TASK_HID) references EXECUTIONPLANITEMTYPE;

alter table ITEMS_TO_ITEMS add constraint ITEMS_TO_ITEMS_FK_R foreign key (CHILD_HID)  references EXECUTIONPLANITEMTYPE;
alter table ITEMS_TO_ITEMS add constraint ITEMS_TO_ITEMS_FK foreign key (PARENT_HID) references EXECUTIONPLANITEMTYPE;

alter table PROCESSVERSION add constraint PROCESS_TASKCANCELLEDMS_FK foreign key (TASKCANCELLEDMILESTONE_HID) references MILESTONETYPE;
alter table PROCESSVERSION add constraint PROCESS_ENDMILESTONE_FK foreign key (ENDMILESTONE_HID) references MILESTONETYPE;
alter table PROCESSVERSION add constraint PROCESS_TO_FULFILMENTPROC_FK foreign key (FULFILMENTPROC_HID) references FULFILMENTPROC;
alter table PROCESSVERSION add constraint PROCESS_STARTMILESTONE_FK foreign key (STARTMILESTONE_HID) references MILESTONETYPE;
alter table PROCESSVERSION add constraint PROCESS_SCHEDULEABLEITEM_FK foreign key (SCHEDULEABLEITEM_HID) references SCHEDULEABLEITEM;

alter table PROCESSSECTIONTYPE add constraint PROCTYPE_TO_SITEM_FK foreign key (SCHEDULEABLEITEM_HID) references SCHEDULEABLEITEM;

alter table MILESTONETYPE add constraint MILESTONETYPE_TO_POINTTYPE_FK foreign key (POINTTYPE_HID) references POINTTYPE;

alter table MILESTONETYPE_FIELD add constraint MILESTONE_TO_FIELD_FK foreign key (MILESTONETYPE_HID) references MILESTONETYPE;
alter table MILESTONETYPE_FIELD add constraint MILESTONE_TO_FIELD_FK_R foreign key (FIELD_HID) references FIELD;

alter table COMPONENT_TO_OBJECTTYPE add constraint COMPONENT_TO_OBJECTTYPE_FK_R foreign key (OBJECTTYPE_HID) references OBJECTTYPE;
alter table COMPONENT_TO_OBJECTTYPE add constraint COMPONENT_TO_OBJECTTYPE_FK foreign key (COMPONENT_HID) references COMPONENT;

alter table COMPONENTGROUPS add constraint CGROUPS_TO_COMPONENT_FK foreign key (COMPONENT_HID) references COMPONENT;
alter table COMPONENTUSERS add constraint COMPONENTUSERS_TO_COMPONENT_FK foreign key (COMPONENT_HID) references COMPONENT;

alter table PROCESS add constraint PROCESS_TO_PROCESSVERSION_FK foreign key (PROCESSVERSION_HID) references PROCESSVERSION;

alter table ORDER_ add constraint ORDER_TO_HEADER_FK foreign key (HEADER_HID) references HEADER;
alter table ORDER_ add constraint ORDER_TO_REQUEST_FK foreign key (REQUEST_HID) references FULFILMENTORDER;

alter table HEADER add constraint HEADER_TO_ORDERHEADER_FK foreign key (ORDERHEADER_HID) references ORDERHEADER;

alter table ORDERHEADER add constraint ORDERHEADER_INVOICEADDRESS_FK foreign key (INVOICEADDRESS_HID) references GEOGRAPHICADDRESSTYPE;
alter table ORDERHEADER add constraint ORDERHEADER_DELIVERYADDRESS_FK foreign key (DELIVERYADDRESS_HID) references GEOGRAPHICADDRESSTYPE;

alter table ORDERHEADER_TO_UDFTYPE add constraint ORDERHEADER_TO_UDFTYPE_FK_R foreign key (UDFTYPE_HID) references UDFTYPE;
alter table ORDERHEADER_TO_UDFTYPE add constraint ORDERHEADER_TO_UDFTYPE_FK foreign key (ORDERHEADER_HID) references ORDERHEADER;

alter table ORDER_TO_LINETYPE add constraint ORDER_TO_LINETYPE_FK_R foreign key (LINETYPE_HID) references LINETYPE;
alter table ORDER_TO_LINETYPE add constraint ORDER_TO_LINETYPE_FK foreign key (ORDER_HID) references ORDER_;

alter table FULFILMENTORDER add constraint FORDER_TO_FULFILMENTPROC_FK foreign key (FULFILMENTPROC_HID) references FULFILMENTPROC;
alter table FULFILMENTORDER add constraint FORDER_TO_ORDERHEADER_FK foreign key (ORDERHEADER_HID) references ORDERHEADER;

alter table ORDERHEADER_TO_SLATYPE add constraint ORDERHEADER_TO_SLATYPE_FK_R foreign key (SLATYPE_HID) references SLATYPE;
alter table ORDERHEADER_TO_SLATYPE add constraint ORDERHEADER_TO_SLATYPE_FK foreign key (ORDERHEADER_HID) references ORDERHEADER;

alter table ADVISORYSTRINGTYPE add constraint ADVISORYSTRING_TO_FORDER_FK foreign key (FULFILMENTORDER_HID) references FULFILMENTORDER;

alter table FORDER_TO_ORDERLINE add constraint FORDER_TO_ORDERLINE_FK foreign key (FULFILMENTORDER_HID) references FULFILMENTORDER;
alter table FORDER_TO_ORDERLINE add constraint FORDER_TO_ORDERLINE_FK_R foreign key (ORDERLINE_HID) references ORDERLINE;

alter table ORDER_TO_FULFILMENTORDER add constraint ORDER_TO_FULFILMENTORDER_FK_R foreign key (FULFILMENTORDER_HID) references FULFILMENTORDER;
alter table ORDER_TO_FULFILMENTORDER add constraint ORDER_TO_FULFILMENTORDER_FK foreign key (ORDER_HID) references ORDER_;

alter table LINETYPE add constraint LINE_TO_ORDERLINE_FK foreign key (ORDERLINE_HID) references ORDERLINE;

alter table ORDERLINE add constraint ORDERLINE_DELIVERYADDRESS_FK foreign key (DELIVERYADDRESS_HID) references GEOGRAPHICADDRESSTYPE;

alter table ORDERLINE_TO_SLATYPE add constraint ORDERLINE_TO_SLATYPE_FK_R foreign key (SLATYPE_HID) references SLATYPE;
alter table ORDERLINE_TO_SLATYPE add constraint ORDERLINE_TO_SLATYPE_FK foreign key (ORDERLINE_HID) references ORDERLINE;
alter table ORDERLINE_TO_UDFTYPE add constraint ORDERLINE_TO_UDFTYPE_FK_R foreign key (UDFTYPE_HID) references UDFTYPE;
alter table ORDERLINE_TO_UDFTYPE add constraint ORDERLINE_TO_UDFTYPE_FK foreign key (ORDERLINE_HID)  references ORDERLINE;
alter table ORDERLINE_TO_CTYPE add constraint ORDERLINE_TO_CTYPE_FK_R foreign key (CHARACTERISTICTYPE_HID) references CHARACTERISTICTYPE;
alter table ORDERLINE_TO_CTYPE add constraint ORDERLINE_TO_CTYPE_FK foreign key (ORDERLINE_HID) references ORDERLINE;
alter table CTYPE_TO_CVALUETYPE add constraint CTYPE_TO_CVALUETYPE_FK_R foreign key (CHARACTERISTICVALUETYPE_HID) references CHARACTERISTICVALUETYPE;
alter table CTYPE_TO_CVALUETYPE add constraint CTYPE_TO_CVALUETYPE_FK foreign key (CHARACTERISTICTYPE_HID) references CHARACTERISTICTYPE;

alter table SUBJECT_TO_EXPDEPENDENCY add constraint SUBJECT_TO_EXPDEPENDENCY_FK_R foreign key (DEPENDENCY_HID) references DEPENDENCYTYPE;
alter table SUBJECT_TO_EXPDEPENDENCY add constraint SUBJECT_TO_EXPDEPENDENCY_FK foreign key (ORCHSUBJECT_HID) references ORCHSUBJECT;
alter table SUBJECT_TO_IMPDEPENDENCY add constraint SUBJECT_TO_IMPDEPENDENCY_FK_R foreign key (DEPENDENCY_HID) references DEPENDENCYTYPE;
alter table SUBJECT_TO_IMPDEPENDENCY add constraint SUBJECT_TO_IMPDEPENDENCY_FK foreign key (ORCHSUBJECT_HID) references ORCHSUBJECT;
alter table SUBJECT_OBSERVERS add constraint OBSERVERS_TO_SUBJECT_FK foreign key (SUBJECT_HID) references ORCHSUBJECT;
alter table SUBJECTDEF_TO_PROPERTY add constraint SUBJECTDEF_TO_PROPERTY_FK_R foreign key (PROPERTY_HID) references PROPERTY;
alter table SUBJECTDEF_TO_PROPERTY add constraint SUBJECTDEF_TO_PROPERTY_FK foreign key (SUBJECTDEF_HID) references ORCHSUBJECT;