DELETE FROM QRTZ_JOB_LISTENERS;
DELETE FROM QRTZ_SIMPLE_TRIGGERS;
DELETE FROM QRTZ_CRON_TRIGGERS;
DELETE FROM QRTZ_FIRED_TRIGGERS;
DELETE FROM QRTZ_BLOB_TRIGGERS;
DELETE FROM QRTZ_TRIGGER_LISTENERS;
DELETE FROM QRTZ_TRIGGERS;
DELETE FROM QRTZ_JOB_DETAILS;
DELETE FROM QRTZ_CALENDARS;
DELETE FROM QRTZ_PAUSED_TRIGGER_GRPS;
DELETE FROM QRTZ_SCHEDULER_STATE;


DELETE FROM RESOURCEBUNDLEPARAMS;
DELETE FROM AUDITITEM;

DELETE FROM MOCLASSIFICATIONVALUE;
DELETE FROM CLASSIFICATION;
DELETE FROM MDCLASSVALUETYPE;
DELETE FROM CLASSIFICATIONGROUP;

DELETE FROM SUBJECT_TO_EXPDEPENDENCY;
DELETE FROM SUBJECT_TO_IMPDEPENDENCY;
DELETE FROM SUBJECT_OBSERVERS;
DELETE FROM SUBJECTDEF_TO_PROPERTY;
DELETE FROM ORCHSUBJECT;
DELETE FROM DEPENDENCYTYPE;
DELETE FROM PROPERTY;

drop table migrationproclogfailed;
drop table migrationproclog;

DELETE FROM FORDER_TO_ORDERLINE;
DELETE FROM ORDERLINE_TO_UDFTYPE;
DELETE FROM LINETYPE;
DELETE FROM ORDERLINE;



SELECT * FROM SCHEDULEABLEITEM;
DELETE FROM SCHEDULEABLEITEM;
DELETE FROM JMSEXCEPTIONS;
DELETE FROM FSYSTEMTYPE_PROPERTY;
DELETE FROM FULFILMENTSYSTEMTYPE;
DELETE FROM POINTTYPE;
DELETE FROM PROPERTY;
DELETE FROM FIELD;

DELETE FROM ADVISORYSTRINGTYPE;
DELETE FROM FULFILMENTORDER;
DELETE FROM FULFILMENTPROC;
DELETE FROM FULFILMENTSYSTEMTYPE;
DELETE FROM HEADER;
DELETE FROM ORDERHEADER_TO_SLATYPE;
DELETE FROM ORDERHEADER_TO_UDFTYPE;
DELETE FROM ORDERLINE_TO_SLATYPE;
DELETE FROM ORDERLINE;
DELETE FROM ORDERHEADER;
DELETE FROM GEOGRAPHICADDRESSTYPE;
DELETE FROM SLATYPE;
DELETE FROM UDFTYPE;


select count(*) from audititem;
