SELECT * FROM AUDITITEM;
SELECT * FROM RESOURCEBUNDLEPARAMS;
SELECT * FROM MOCLASSIFICATIONVALUE;
SELECT * FROM CLASSIFICATIONGROUP;
SELECT * FROM CLASSIFICATION;
SELECT * FROM MDCLASSVALUETYPE;


DELETE FROM RESOURCEBUNDLEPARAMS;
DELETE FROM AUDITITEM;

DELETE FROM MOCLASSIFICATIONVALUE;
DELETE FROM MDCLASSVALUETYPE;
DELETE FROM CLASSIFICATION;
DELETE FROM CLASSIFICATIONGROUP;
DELETE FROM MOCLASSIFICATIONVALUE ;
DELETE FROM ORDERREQUESTQUEUE;
DELETE FROM REQUEST;
DELETE FROM JMSEXCEPTIONS;
DELETE FROM SUBJECTDEF_TO_PROPERTY;
DELETE FROM SUBJECT_TO_IMPDEPENDENCY;
DELETE FROM PROPERTY;
DELETE FROM ORCHSUBJECT;
DELETE FROM DEPENDENCYTYPE;


SELECT * FROM ORCHSUBJECT
SELECT * FROM REQUEST;
DROP TABLE REQUEST;
create table REQUEST (
        HID number(19,0) not null,
        HVER number(10,0),
        REQUEST_ID varchar2(15 char) unique,
        REQUEST_TEXT clob,
        UPDATED timestamp,
        primary key (HID)
    );
SELECT * FROM REQUEST;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'REQUEST';

SELECT * FROM ORDERREQUESTQUEUE;


SELECT * FROM QRTZ_JOB_DETAILS;
SELECT * FROM QRTZ_JOB_LISTENERS;
SELECT * FROM QRTZ_TRIGGERS;
SELECT * FROM QRTZ_SIMPLE_TRIGGERS;
SELECT * FROM QRTZ_CRON_TRIGGERS;
SELECT * FROM QRTZ_BLOB_TRIGGERS;
SELECT * FROM QRTZ_TRIGGER_LISTENERS;
SELECT * FROM QRTZ_CALENDARS;
SELECT * FROM QRTZ_PAUSED_TRIGGER_GRPS;
SELECT * FROM QRTZ_FIRED_TRIGGERS;
SELECT * FROM QRTZ_SCHEDULER_STATE;
SELECT * FROM QRTZ_LOCKS;

DELETE FROM QRTZ_JOB_LISTENERS;
DELETE FROM QRTZ_JOB_DETAILS;
DELETE FROM QRTZ_SIMPLE_TRIGGERS;
DELETE FROM QRTZ_CRON_TRIGGERS;
DELETE FROM QRTZ_FIRED_TRIGGERS;
DELETE FROM QRTZ_BLOB_TRIGGERS;
DELETE FROM QRTZ_TRIGGER_LISTENERS;
DELETE FROM QRTZ_TRIGGERS;
DELETE FROM QRTZ_CALENDARS;
DELETE FROM QRTZ_PAUSED_TRIGGER_GRPS;
DELETE FROM QRTZ_SCHEDULER_STATE;

SELECT * FROM ORDER_;
SELECT * FROM COMPONENT;
SELECT * FROM PROCESS;

create table MIGRATIONPROCLOG (
        HID number(19,0) not null,
        MIGKEY varchar2(255 char),
        MIGROW number(19,0),
        MIGTYPE number(19,0),
        primary key (HID)
    );
SELECT * FROM MIGRATIONPROCLOG WHERE MIGRATIONPROCLOG.MIGTYPE = 1;
SELECT COUNT(*) FROM ORDER_;
SELECT COUNT(*) FROM EXECUTIONPLAN;
SELECT COUNT(*) FROM MIGRATIONPROCLOG;
SELECT COUNT(*) FROM ORCHSUBJECT;


DELETE FROM MIGRATIONPROCLOG;

create index orders_num_index on orders(num);
SELECT * from user_constraints where table_name = 'orders'; 
SELECT * FROM ORDERREQUESTQUEUE;
SELECT * FROM JMSEXCEPTIONS;
