SELECT EXECUTIONPLAN.HID FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.UNIQUEID='bug2-19308';
SELECT * FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.UNIQUEID='bug2-19308';
SELECT * FROM AUDITITEM WHERE AUDITITEM.Key = 'bug2-19308';
SELECT * FROM RESOURCEBUNDLEPARAMS WHERE RESOURCEBUNDLEPARAMS.AUDITITEM_HID = 780;
SELECT * FROM UDFTYPE WHERE UDFTYPE.HID = 550;
SELECT * FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.HID = 550;
SELECT * FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 400;
SELECT * FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 500;
SELECT * FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 400;
SELECT * FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 500;
SELECT * FROM PROCESSVERSION_TO_MILESTONE WHERE PROCESSVERSION_TO_MILESTONE.PROCESSVERSION_HID = 400;
SELECT * FROM MILESTONETYPE WHERE MILESTONETYPE.HID = 752 ;
SELECT * FROM MILESTONETYPE_PROPERTY WHERE MILESTONETYPE_PROPERTY.MILESTONETYPE_HID = 752 ;
SELECT * FROM MILESTONETYPE WHERE MILESTONETYPE.HID = 752;
SELECT * FROM PROCESSVERSION WHERE PROCESSVERSION.HID = 400;
SELECT * FROM AUDITITEM WHERE AUDITITEM.Key = 'order001';
SELECT * FROM ORDER_ WHERE ORDER_.HID = 138;
SELECT * FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 138;
SELECT * FROM ORDERLINE WHERE ORDERLINE.HID = 138;
SELECT * FROM LINETYPE WHERE LINETYPE.HID = 138;
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FORDER_TO_ORDERLINE_FK_R';
SELECT * FROM LINETYPE;
SELECT * FROM ORDER_TO_LINETYPE WHERE ORDER_TO_LINETYPE.ORDER_HID = 138 ;
SELECT * FROM LINETYPE WHERE LINETYPE.HID = 138;
DELETE FROM LINETYPE WHERE LINETYPE.HID = 
SELECT * FROM ORDERLINE WHERE ORDERLINE.HID = 271;
SELECT * FROM ORDERLINE_TO_UDFTYPE WHERE ORDERLINE_TO_UDFTYPE.ORDERLINE_HID = 271;
SELECT * FROM ORDERLINE_TO_CTYPE WHERE ORDERLINE_TO_CTYPE.ORDERLINE_HID = 271;
SELECT * FROM FORDER_TO_ORDERLINE WHERE FORDER_TO_ORDERLINE.ORDERLINE_HID = 271;
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FORDER_TO_ORDERLINE_FK_R';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FORDER_TO_ORDERHEADER_FK';
SELECT * FROM ORDERHEADER WHERE ORDERHEADER.HID = 271;
SELECT * FROM ORDERHEADER_TO_SLATYPE WHERE ORDERHEADER_TO_SLATYPE.ORDERHEADER_HID = 271;
SELECT FULFILMENTORDER.HID FROM FULFILMENTORDER WHERE FULFILMENTORDER.ORDERHEADER_HID = 271 ;
SELECT FULFILMENTORDER.HID FROM FULFILMENTORDER WHERE FULFILMENTORDER.ORDERHEADER_HID = 271;
SELECT * FROM ORDER_ INNER JOIN HEADER ON ORDER_.HEADER_HID = HEADER.HID INNER JOIN ORDERHEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE ORDERHEADER.ORDERREF = 'AOPD-AUTOTEST-1309495598453';
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK87D2B513255DDFA';
SELECT * FROM EXECUTIONPLAN;
SELECT * FROM FULFILMENTORDER WHERE FULFILMENTORDER.HID = 12;
SELECT * FROM ORDER_
SELECT * FROM COMPONENT;
SELECT * FROM ORDER_ INNER JOIN HEADER ON ORDER_.HEADER_HID = HEADER.HID INNER JOIN ORDERHEADER ON ORDERHEADER.HID = HEADER.ORDERHEADER_HID WHERE ORDERHEADER.ORDERREF = 'AOPD-AUTOTEST-1309497757984';
SELECT * FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.UNIQUEID='AOPD-AUTOTEST-1309497759468-1309497759578';
SELECT * FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.UNIQUEID='AOPD-AUTOTEST-1309497759468-1309497759578';
SELECT * FROM AUDITITEM WHERE AUDITITEM.Key = 'AOPD-AUTOTEST-1309497759468-1309497759578';
SELECT * FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.PLAN_HID = 65;
DELETE FROM UDFTYPE WHERE UDFTYPE.PLANITEM_HID = 
SELECT * FROM UDFTYPE WHERE UDFTYPE.PLANITEM_HID = 195;
SELECT * FROM ITEMS_TO_ITEMS WHERE ITEMS_TO_ITEMS.PARENT_HID = 195;
SELECT * FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.HID = 195 ;
SELECT * FROM UDFTYPE WHERE UDFTYPE.PLANITEM_HID = 196;
SELECT * FROM EXECUTIONPLAN;
SELECT * FROM ORDER_;
SELECT USER_TABLES.TABLE_NAME FROM USER_TABLES;
SELECT count(*) FROM TEACHER;
DROP TABLE HOME_TEST_1 CASCADE;
DROP TABLE TEACHER;
SELECT * FROM RESOURCEBUNDLEPARAMS;
DELETE FROM RESOURCEBUNDLEPARAMS;
SELECT * FROM AUDITITEM;
DELETE FROM AUDITITEM;
DELETE FROM ACTIONS;
DELETE FROM DEPENDENCY;
DELETE FROM DEPENDENCYTYPE;
DELETE FROM FIELD;
DELETE FROM FSYSTEMTYPE_PROPERTY;
DELETE FROM FULFILMENTPROC;
DELETE FROM FULFILMENTSYSTEMTYPE;
DELETE FROM GEOGRAPHICADDRESSTYPE;
DELETE FROM JEOPARDYDEFTYPE;
DELETE FROM JEOPARDYINFOTYPE;
DELETE FROM JEOPARDYSUPERTYPE;
DELETE FROM JEOPARDYSUPERTYPE_TO_DEF;
DELETE FROM JMSEXCEPTIONS;
DELETE FROM MILESTONETYPE;
DELETE FROM MILESTONETYPE_FIELD;
DELETE FROM MILESTONETYPE_PROPERTY;
DELETE FROM OBJECTTYPE;
DELETE FROM PLANITEMDEPENDENCYTYPE;
DELETE FROM ORCHSUBJECT;
DELETE FROM POINTTYPE;
DELETE FROM PROCESSSECTIONTYPE;
DELETE FROM PROCESSVERSION;
DELETE FROM PROCESSVERSION_TO_SECTION;
DELETE FROM PROPERTY;
DELETE FROM REQUEST;
DELETE FROM SCHEDULEABLEITEM;
DELETE FROM STARTTIMEDEPENDENCYTYPE;
DELETE FROM SUBJECT_OBSERVERS;
DELETE FROM SUBJECT_TO_EXPDEPENDENCY;
DELETE FROM IPC_PO_GEN;
show parameter cursor
DELETE FROM RESOURCEBUNDLEPARAMS;
DELETE FROM AUDITITEM;
DELETE FROM CLASSIFICATIONGROUP;
SELECT * FROM PROPERTY;
SELECT * FROM FSYSTEMTYPE_PROPERTY;
SELECT * FROM SCHEDULEABLEITEM;
SELECT * FROM DEPENDENCYTYPE;
SELECT * FROM GEOGRAPHICADDRESSTYPE;
DELETE FROM FULFILMENTSYSTEMTYPE;
DELETE FROM IPC_PO_GEN;
SELECT * FROM IPC_PO_GEN;
DELETE FROM SCHEDULEABLEITEM;
DELETE FROM SCHEDULEABLEITEM WHERE SCHEDULEABLEITEM.HID = 273
SELECT * FROM Audititem;
SELECT * FROM RESOURCEBUNDLEPARAMS;
SELECT * FROM EXECUTIONPLAN
SELECT * FROM JEOPARDYINFOTYPE;
SELECT * FROM PROCESS;
SELECT * FROM PROCESSVERSION;
SELECT * FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 49;
SELECT * FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 49;
SELECT PROCESSSECTIONTYPE.SCHEDULEABLEITEM_HID FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 49;
SELECT * FROM EXECUTIONPLAN;
SELECT * FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.PLAN_HID = 10;
SELECT * FROM PROCESSVERSION WHERE PROCESSVERSION.HID = 1;
SELECT * FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 1;
SELECT * FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 1;
SELECT * FROM SCHEDULEABLEITEM;
SELECT * FROM PROCESSVERSION;
DELETE FROM SCHEDULEABLEITEM;
SELECT * FROM IPC_PO_GEN;
SELECT * FROM GEOGRAPHICADDRESSTYPE;
DELETE FROM GEOGRAPHICADDRESSTYPE;
DELETE FROM FULFILMENTSYSTEMTYPE;

SELECT * FROM FIELD;
SELECT * FROM FSYSTEMTYPE_PROPERTY;
SELECT * FROM FULFILMENTPROC;
SELECT * FROM FULFILMENTSYSTEMTYPE;
SELECT * FROM MILESTONETYPE;
SELECT * FROM MILESTONETYPE_FIELD;
SELECT * FROM MILESTONETYPE_PROPERTY;
SELECT * FROM POINTTYPE;
SELECT * FROM PROCESSSECTIONTYPE;
SELECT * FROM PROCESSVERSION;
SELECT * FROM PROCESSVERSION_TO_SECTION;
SELECT * FROM PROPERTY; 
SELECT * FROM SCHEDULEABLEITEM;
SELECT * FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 49;
SELECT * FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 49;
SELECT PROCESSSECTIONTYPE.SCHEDULEABLEITEM_HID FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 49;
SELECT * FROM EXECUTIONPLAN;
SELECT * FROM EXECUTIONPLANITEMTYPE WHERE EXECUTIONPLANITEMTYPE.PLAN_HID = 10;
SELECT * FROM PROCESSVERSION WHERE PROCESSVERSION.HID = 1;
SELECT * FROM PROCESSVERSION_TO_SECTION WHERE PROCESSVERSION_TO_SECTION.PROCESSVERSION_HID = 1;
SELECT * FROM PROCESSSECTIONTYPE WHERE PROCESSSECTIONTYPE.HID = 1;
SELECT * FROM PROCESSVERSION_TO_SECTION;
SELECT * FROM SCHEDULEABLEITEM;
SELECT * FROM PROCESSVERSION WHERE PROCESSVERSION.SCHEDULEABLEITEM_HID = 62;

SELECT * FROM SCHEDULEABLEITEM;
SELECT * FROM FSYSTEMTYPE_PROPERTY;
SELECT * FROM PROPERTY;
SELECT * FROM FULFILMENTPROC;
SELECT * FROM FULFILMENTSYSTEMTYPE;

DELETE FROM FSYSTEMTYPE_PROPERTY;
DELETE FROM PROPERTY;
DELETE FROM SCHEDULEABLEITEM;
DELETE FROM FULFILMENTPROC;
DELETE FULFILMENTSYSTEMTYPE;

SELECT * FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.STATUS = 'COMPLETE';
SELECT * FROM TEACHER;
SELECT * FROM COMPONENT;
SELECT * FROM ORCHSUBJECT;
SELECT *
SELECT *
SELECT * 
SELECT * 
SELECT * 
SELECT *
SELECT *
SELECT * 
SELECT * 
SELECT * 
SELECT *
SELECT *
SELECT * 
SELECT * 
SELECT * 
SELECT *
SELECT *
DELETE FROM STUDENT_TO_TEACHER;
DELETE FROM TEACHER;
DELETE FROM STUDENT;
DELETE FROM STUDENTCARD;
-----delete dirt data
DELETE FROM MILESTONETYPE_FIELD;
DELETE FROM MILESTONETYPE_PROPERTY;
DELETE FROM PROCESSVERSION_TO_SECTION;
DELETE FROM FSYSTEMTYPE_PROPERTY;
DELETE FROM PROPERTY;
DELETE FROM PROCESSVERSION;
DELETE FROM FULFILMENTPROC;
DELETE FROM FULFILMENTSYSTEMTYPE;
DELETE FROM PROCESSSECTIONTYPE; 
DELETE FROM FIELD;
DELETE FROM SCHEDULEABLEITEM;
DELETE FROM MILESTONETYPE;
DELETE FROM POINTTYPE;
DELETE FROM ORCHSUBJECT;
--constraints FKE1D84E588D48F61
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FKE1D84E588D48F61';
SELECT * FROM EXECUTIONPLAN WHERE EXECUTIONPLAN.UNIQUEID LIKE 'muep11-%';
SELECT * FROM EXECUTIONPLAN;
SELECT * FROM AUDITITEM WHERE KEY = 'EP05';
DELETE FROM RESOURCEBUNDLEPARAMS WHERE RESOURCEBUNDLEPARAMS.AUDITITEM_HID >= 1 AND RESOURCEBUNDLEPARAMS.AUDITITEM_HID <= 2
DELETE FROM AUDITITEM WHERE AUDITITEM.HID >= 1 AND AUDITITEM.HID <= 1
SELECT AUDITITEM.HID FROM AUDITITEM WHERE AUDITITEM.PARENT_HID = 1 AND AUDITITEM.HASCHILD = '0'
SELECT * FROM COMPONENT;
SELECT * FROM ORDER_;
SELECT * FROM AUDITITEM;
SELECT * FROM ORCHSUBJECT;

DELETE FROM RESOURCEBUNDLEPARAMS;
DELETE FROM AUDITITEM;
SELECT COUNT(*) FROM ORDER_;
SELECT * FROM FIELD;
SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SYS_C00114461';
SELECT * FROM EXECUTIONPLAN;

-- delet orchjubject
DELETE FROM SUBJECTDEF_TO_PROPERTY;
DELETE FROM SUBJECT_TO_EXPDEPENDENCY;
DELETE FROM SUBJECT_TO_IMPDEPENDENCY;
DELETE FROM FIELD;
DELETE FROM JMSEXCEPTIONS;
DELETE FROM SUBJECT_OBSERVERS;
DELETE FROM DEPENDENCYTYPE;
DELETE FROM PROPERTY;
DELETE FROM PROCESSSECTIONTYPE;
DELETE FROM SCHEDULEABLEITEM;
DELETE FROM ORCHSUBJECT;

SELECT * FROM AUDITITEM;
SELECT * FROM RESOURCEBUNDLEPARAMS;