CREATE TABLE DEPT
(
DEPTNO NUMBER(19) NOT NULL,
DEPTNAME VARCHAR2(30),
CONSTRAINT PK_DEPT PRIMARY KEY(DEPTNO)
);
CREATE TABLE EMP
(
EMPNO NUMBER(19) NOT NULL,
EMPNAME VARCHAR2(30),
DEPTNO NUMBER(19),
CONSTRAINT PK_EMP PRIMARY KEY(EMPNO),
CONSTRAINT FK_EMP_DEPT FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO)on delete cascade
);
DROP TABLE EMP;
SELECT * FROM DEPT;
SELECT * FROM EMP;
INSERT INTO DEPT VALUES(1,'dept1');
INSERT INTO EMP VALUES(1, 'emp1', 1);
DELETE FROM DEPT WHERE DEPT.DEPTNO = 1;
DELETE FROM EMP WHERE EMPNO = 1;


UPDATE FK_EMP_DEPT ON DELETE CASCADE;
ALTER TABLE EMP
(
UPDATE FK_EMP_DEPT ON DELETE CASCADE;
)


DELETE FROM GEOGRAPHICADDRESSTYPE;
DELETE FROM JMSEXCEPTIONS;

alter table CTYPE_TO_CVALUETYPE drop constraint CTYPE_TO_CVALUETYPE_FK_R;
alter table CTYPE_TO_CVALUETYPE add constraint CTYPE_TO_CVALUETYPE_FK_R foreign key (CHARACTERISTICVALUETYPE_HID) references CHARACTERISTICVALUETYPE on delete cascade;
alter table CTYPE_TO_CVALUETYPE drop constraint CTYPE_TO_CVALUETYPE_FK;
alter table CTYPE_TO_CVALUETYPE add constraint CTYPE_TO_CVALUETYPE_FK foreign key (CHARACTERISTICTYPE_HID) references CHARACTERISTICTYPE on delete cascade;
alter table ORDERLINE_TO_CTYPE drop constraint ORDERLINE_TO_CTYPE_FK_R;
alter table ORDERLINE_TO_CTYPE add constraint ORDERLINE_TO_CTYPE_FK_R foreign key (CHARACTERISTICTYPE_HID) references CHARACTERISTICTYPE on delete cascade;
alter table ORDERLINE_TO_CTYPE drop constraint ORDERLINE_TO_CTYPE_FK;
alter table ORDERLINE_TO_CTYPE add constraint ORDERLINE_TO_CTYPE_FK foreign key (ORDERLINE_HID) references ORDERLINE on delete cascade;
 
   
SELECT * FROM ORDERLINE;   
SELECT * FROM ORDERLINE_TO_CTYPE;
SELECT * FROM CHARACTERISTICTYPE;
SELECT * FROM CTYPE_TO_CVALUETYPE;
SELECT * FROM CHARACTERISTICVALUETYPE;
DELETE FROM CTYPE_TO_CVALUETYPE;
DELETE FROM CHARACTERISTICVALUETYPE;
DELETE FROM CHARACTERISTICTYPE;