English Patient
---------------

The King insisted that he would find some way to prove beyond dispute, that his wife was fairest of all women. "I will hide you in your room where we sleep." said Candaules. Candaules tells Gygets that the Queen has the same practice every night. She takes off her clothes and puts them on the chair by the door to her room. And from where you stand, you will be able to gaze on her at your leisure. And that evening,it's exactly as the King has yold him. She goes to chair, removes her clothes one by one, until she's standing naked in full view if Gyges. And indeed, she was more lovely than he could have imageined. But then, the Queen looked up and saw Gyges concealed in the shadows. And although she said nothing, she shuddered.And the next day, she sends for, for Gyges and challenged him. And hearing his story, this is what she said. She said, "Either you must submit to death for gazing on that which you should not, or else kill my husband who has shamed me, and become King in his place." So Gyges kills the King, marries the Queen and becomes ruler of Lydia for 28 years.
